# apt
# Autogenerated from man page /usr/share/man/man8/apt.8.gz
# using Deroffing man parser
complete -c apt -s h -l help --description 'Show a short usage summary.'
complete -c apt -s v -l version --description 'Show the program version.'
complete -c apt -s c -l config-file --description 'Configuration File; Specify a configuration file to use.'
complete -c apt -s o -l option --description 'Set a Configuration Option; This will set an ar… [See Man Page]'
complete -c apt -l installed --description '.'
complete -c apt -l upgradable --description '.'
complete -c apt -l all-versions --description 'are supported.  search.'
complete -c apt -o f- -l no-f --description '.'
complete -c apt -s f --description 'or several other variations.'
complete -c apt -l with-new-pkgs --description 'enabled by default.  SEE ALSO.'

