# audacious
# Autogenerated from man page /usr/share/man/man1/audacious.1.gz
# using Deroffing man parser
complete -c audacious -s h -l help --description 'Show a brief list of options. PP  Opening files:.'
complete -c audacious -s e -l enqueue --description 'Add the files on the command line to the curren… [See Man Page]'
complete -c audacious -s E -l enqueue-to-temp --description 'Add the files on the command line to a temporar… [See Man Page]'
complete -c audacious -s p -l play --description 'If currently playing, go to the beginning of th… [See Man Page]'
complete -c audacious -s u -l pause --description 'If currently playing, pause; if paused, resume playing.'
complete -c audacious -s t -l play-pause --description 'If currently playing, pause; otherwise, begin playing.'
complete -c audacious -s s -l stop --description 'Stop playing and go to the beginning of the song.'
complete -c audacious -s r -l rew --description 'Go to the previous song in the playlist.'
complete -c audacious -s f -l fwd --description 'Go to the next song in the playlist. PP  Miscellaneous:.'
complete -c audacious -s m -l show-main-window --description 'Show the Audacious window if it is hidden and b… [See Man Page]'
complete -c audacious -s j -l show-jump-box --description 'Show the Jump to Song window.'
complete -c audacious -s H -l headless --description 'Start in command-line mode; i. e.'
complete -c audacious -s q -l quit-after-play --description 'Exit as soon as playback stops, or immediately … [See Man Page]'
complete -c audacious -s v -l version --description 'Print version information and exit.'
complete -c audacious -s V -l verbose --description 'Print debugging output while running.'

