# botti
# Autogenerated from man page /usr/share/man/man1/botti.1.gz
# using Type1
complete -c botti -l config --description 'Specify the configuration file location.'
complete -c botti -l home --description 'Specify the irssi home directory location.'
complete -c botti -s l -l load --description 'Specify a module to load.  By default, it is "bot".'
complete -c botti -l session --description 'Option used by the /UPGRADE command.'
complete -c botti -s '?' -l help --description 'Print instructions.'

