# ccze
# Autogenerated from man page /usr/share/man/man1/ccze.1.gz
# using Deroffing man parser
complete -c ccze -s a -l argument --description 'Use this option to pass ARGUMENTS to the specified PLUGIN.'
complete -c ccze -s A -l raw-ansi --description 'If one wants to enable raw ANSI color sequences… [See Man Page]'
complete -c ccze -s c -l color --description 'Set the color of the keyword KEY to COLOR, like… [See Man Page]'
complete -c ccze -s C -l convert-date --description 'Convert unix timestamp to readable date format … [See Man Page]'
complete -c ccze -s F -l rcfile --description 'Read rcfile as a configuration file upon startu… [See Man Page]'
complete -c ccze -s h -l html --description 'Instead of colorising the input onto the consol… [See Man Page]'
complete -c ccze -s l -l list-plugins --description 'List all available (loaded) plugins, along with… [See Man Page]'
complete -c ccze -s m -l mode --description 'Change the output mode.'
complete -c ccze -s o -l options --description 'CCZE is able to toggle some of its features with this option.'
complete -c ccze -s p -l plugin --description 'While the default action is to load all plugins… [See Man Page]'
complete -c ccze -s r -l remove-facility --description 'Syslog-ng puts the facility level before log messages.'
complete -c ccze -l help --description 'Show summary of options and exit.'
complete -c ccze -s V -l version --description 'Show version of program.'

