# ccze-cssdump
# Autogenerated from man page /usr/share/man/man1/ccze-cssdump.1.gz
# using Deroffing man parser
complete -c ccze-cssdump -s F -l rcfile --description 'Read rcfile as a configuration file upon startup.'
complete -c ccze-cssdump -s l -l load --description 'Load the default configuration files upon startup.'
complete -c ccze-cssdump -l help --description 'Show summary of options and exit.'
complete -c ccze-cssdump -s V -l version --description 'Show version of program.  FILES.'

