# cgdisk
# Autogenerated from man page /usr/share/man/man8/cgdisk.8.gz
# using Deroffing man parser
complete -c cgdisk -o 'a.' --description 'free space: Instead of using ncurses, when -a i… [See Man Page]'

