# checksendmail
# Autogenerated from man page /usr/share/man/man8/checksendmail.8.gz
# using Darwin man parser
complete -c checksendmail -s a --description 'Show aliasing of local addresses in mail addres… [See Man Page]'
complete -c checksendmail -s d --description 'Precede each address translation line with rule… [See Man Page]'
complete -c checksendmail -s C --description 'Use the sendmail configuration file file.'
complete -c checksendmail -s b --description 'Use the specified sendmail_binary as the path t… [See Man Page]'
complete -c checksendmail -s l --description 'Log sendmail address test mode debugging output to log_file.'
complete -c checksendmail -s r --description 'Use resolve as the input file for the addresses… [See Man Page]'
complete -c checksendmail -s T --description 'Use test. address as the single address to test.'

