# cheetah-compile
# Autogenerated from man page /usr/share/man/man1/cheetah-compile.1.gz
# using Deroffing man parser
complete -c cheetah-compile -l idir --description 'Input directories(default: current dir).'
complete -c cheetah-compile -l odir --description 'Output directories (default: current dir).'
complete -c cheetah-compile -l iext --description 'Input extension.'
complete -c cheetah-compile -l oext --description 'Output extension.'
complete -c cheetah-compile -s R --description 'Recurse subdirectories looking for input files.'
complete -c cheetah-compile -l debug --description 'Print lots of diagnostic output to the standard… [See Man Page]'
complete -c cheetah-compile -l env --description 'Print the environment in the searchList.'
complete -c cheetah-compile -l flat --description 'No destination subdirectories.'
complete -c cheetah-compile -l nobackup --description 'Do not make backups.'
complete -c cheetah-compile -l pickle --description 'unpickle FILE and put that output in the searchList.'
complete -c cheetah-compile -l stdout -s p --description 'Output to standard output file descriptor (pipe… [See Man Page]'

