# cheetah
# Autogenerated from man page /usr/share/man/man1/cheetah.1.gz
# using Deroffing man parser
complete -c cheetah -l idir --description 'Input directories(default: current dir).'
complete -c cheetah -l odir --description 'Output directories (default: current dir).'
complete -c cheetah -l iext --description 'Input extension.'
complete -c cheetah -l oext --description 'Output extension.'
complete -c cheetah -s R --description 'Recurse subdirectories looking for input files.'
complete -c cheetah -l debug --description 'Print lots of diagnostic output to the standard… [See Man Page]'
complete -c cheetah -l env --description 'Print the environment in the searchList.'
complete -c cheetah -l flat --description 'No destination subdirectories.'
complete -c cheetah -l nobackup --description 'Do not make backups.'
complete -c cheetah -l pickle --description 'unpickle FILE and put that output in the searchList.'
complete -c cheetah -l stdout -s p --description 'Output to standard output file descriptor (pipe… [See Man Page]'

