# clambc
# Autogenerated from man page /usr/share/man/man1/clambc.1.gz
# using Deroffing man parser
complete -c clambc -l help -s h --description 'Show help.'
complete -c clambc -l version -s V --description 'Show version.'
complete -c clambc -l debug --description 'Show debug.'
complete -c clambc -l force-interpreter -s f --description 'Force using the interpreter instead of the JIT.'
complete -c clambc -l trust-bytecode -s t --description 'Trust loaded bytecode (default yes).'
complete -c clambc -l info -s i --description 'Print information about bytecode.'
complete -c clambc -l printsrc -s p --description 'Print bytecode source.'
complete -c clambc -l printbcir -s c --description 'Print IR of bytecode signature.'
complete -c clambc -l input -s r --description 'Input file to run the bytecode on.'
complete -c clambc -l trace -s T --description 'Set bytecode trace level 0. 7 (default 7).'
complete -c clambc -l no-trace-showsource --description 'Don\'t show source line during tracing.'
complete -c clambc -l bytecode-statistics --description 'Collect and print bytecode execution statistics.'

