# clamsubmit
# Autogenerated from man page /usr/share/man/man1/clamsubmit.1.gz
# using Type1
complete -c clamsubmit -s h -s '?' --description 'Display help to stderr and exit.'
complete -c clamsubmit -s e --description 'Required option for setting the email address f… [See Man Page]'
complete -c clamsubmit -s n --description 'Submit a file that reports as a false negative … [See Man Page]'
complete -c clamsubmit -s N --description 'Required option for setting the name of the sen… [See Man Page]'

