# clang-apply-replacements-3
# Autogenerated from man page /usr/share/man/man1/clang-apply-replacements-3.6.1.gz
# using Deroffing man parser
complete -c clang-apply-replacements-3 -o format --description 'Use -style to choose formatting style.'
complete -c clang-apply-replacements-3 -o style --description 'LLVM, Google, Chromium, Mozilla, WebKit.'
complete -c clang-apply-replacements-3 -o style-config --description 'describing a formatting style to use for format… [See Man Page]'
complete -c clang-apply-replacements-3 -o help --description '.'
complete -c clang-apply-replacements-3 -o help-list --description '.'
complete -c clang-apply-replacements-3 -o remove-change-desc-files --description 'merging/replacing.'
complete -c clang-apply-replacements-3 -o version --description 'SEE ALSO The full documentation for clang-apply… [See Man Page]'

