# clang-tidy-3
# Autogenerated from man page /usr/share/man/man1/clang-tidy-3.6.1.gz
# using Deroffing man parser
complete -c clang-tidy-3 -o analyze-temporary-dtors --description 'clang-analyzer- checks.'
complete -c clang-tidy-3 -o checks --description 'prefix.'
complete -c clang-tidy-3 -o config --description '-config="{Checks: \'*\', CheckOptions: [{key: x, value: y}]}".'
complete -c clang-tidy-3 -o dump-config --description 'should be used along with a file name (and \'--\'… [See Man Page]'
complete -c clang-tidy-3 -o export-fixes --description 'stored fixes can be applied to the input source… [See Man Page]'
complete -c clang-tidy-3 -o fix -o fix-errors --description 'clang-tidy will bail out if any compilation errors were found.'
complete -c clang-tidy-3 -o header-filter --description 'headers to output diagnostics from.'
complete -c clang-tidy-3 -o line-filter --description 'warnings.  Can be used together with -header-filter.'
complete -c clang-tidy-3 -o list-checks --description '-checks=\'*\' to list all available checks.'
complete -c clang-tidy-3 -o help --description '.'
complete -c clang-tidy-3 -o help-list --description '.'
complete -c clang-tidy-3 -o version --description '.'
complete -c clang-tidy-3 -o enable-check-profile --description '.'
complete -c clang-tidy-3 -o extra-arg --description '.'
complete -c clang-tidy-3 -o extra-arg-before --description '.'
complete -c clang-tidy-3 -o 'header-filter.' --description 'array of objects:.'
complete -c clang-tidy-3 -s p --description '.'
complete -c clang-tidy-3 -o system-headers --description '.'
complete -c clang-tidy-3 -l - --description '.'

