# clang-check-3
# Autogenerated from man page /usr/share/man/man1/clang-check-3.6.1.gz
# using Deroffing man parser
complete -c clang-check-3 -o help --description '.'
complete -c clang-check-3 -o help-list --description '.'
complete -c clang-check-3 -o version --description '.'
complete -c clang-check-3 -o analyze --description '.'
complete -c clang-check-3 -o ast-dump --description '.'
complete -c clang-check-3 -o ast-dump-filter -o ast-print -o ast-list --description '.'
complete -c clang-check-3 -o extra-arg --description '.'
complete -c clang-check-3 -o extra-arg-before --description '.'
complete -c clang-check-3 -o fix-what-you-can --description '.'
complete -c clang-check-3 -o fixit --description '.'
complete -c clang-check-3 -s p --description '.'

