# cpufreq-selector
# Autogenerated from man page /usr/share/man/man1/cpufreq-selector.1.gz
# using Type1
complete -c cpufreq-selector -s '?' --description '--help         " 10  Show summary of options.'
complete -c cpufreq-selector -s c --description '--cpu=NUMBER         " 10  number of CPU to set.'
complete -c cpufreq-selector -s g --description '--governor=GOV         " 10  CPU governor to us… [See Man Page]'

