# cracklib-packer
# Autogenerated from man page /usr/share/man/man8/cracklib-packer.8.gz
# using Deroffing man parser
complete -c cracklib-packer -s T --description 'option.  cracklib-format has a hook for this.'

