# cracklib-unpacker
# Autogenerated from man page /usr/share/man/man8/cracklib-unpacker.8.gz
# using Deroffing man parser
complete -c cracklib-unpacker -s T --description 'option.  cracklib-format has a hook for this.'

