# dcut
# Autogenerated from man page /usr/share/man/man1/dcut.1.gz
# using Deroffing man parser
complete -c dcut -s c -l config --description 'Use config file filename.'
complete -c dcut -s d -l debug --description 'Print debug messages.'
complete -c dcut -s h -l help --description 'Print help information and exit.'
complete -c dcut -l host --description 'Upload to host (as found in the dput configuration).'
complete -c dcut -s m -l maintainer --description 'Use maintainer (full email) for the uploader fi… [See Man Page]'
complete -c dcut -s k -l keyid --description 'Use keyid for signing.'
complete -c dcut -s O -l output --description 'Write commands file to filename instead of uploading.'
complete -c dcut -s P -l passive --description 'Use passive ftp instead of active.'
complete -c dcut -s s -l simulate --description 'Simulate an upload only.'
complete -c dcut -s U -l upload --description 'Upload commands file.'
complete -c dcut -s i -l input --description 'Read an input changes file to create a commands… [See Man Page]'
complete -c dcut -s v -l version --description 'Print version information and exit.'
complete -c dcut -l ---BEGIN --description 'Hash: SHA1.'
complete -c dcut -l ---END --description 'To upload a GPG signed commands file that remov… [See Man Page]'

