# dm-tool
# Autogenerated from man page /usr/share/man/man1/dm-tool.1.gz
# using Deroffing man parser
complete -c dm-tool -s h -l help --description 'Show help options.'
complete -c dm-tool -l version --description 'Show release version.'
complete -c dm-tool -l session-bus --description 'Attempt to connect to the display manager using… [See Man Page]'

