# docker-export
# Autogenerated from man page /usr/share/man/man1/docker-export.1.gz
# using Deroffing man parser
complete -c docker-export -l help --description '  Print usage statement.'
complete -c docker-export -s o -l output --description '  Write to a file, instead of STDOUT EXAMPLES.'

