# docker-volume-ls
# Autogenerated from man page /usr/share/man/man1/docker-volume-ls.1.gz
# using Deroffing man parser
complete -c docker-volume-ls -s f -l filter --description '  Provide filter values (i. e.  \'dangling=true\').'
complete -c docker-volume-ls -l help --description '  Print usage statement.'
complete -c docker-volume-ls -s q -l quiet --description '  Only display volume names HISTORY.'

