# docker-network-create
# Autogenerated from man page /usr/share/man/man1/docker-network-create.1.gz
# using Deroffing man parser
complete -c docker-network-create -l driver --description 'When you install Docker Engine it creates a bri… [See Man Page]'
complete -c docker-network-create -l aux-address --description '.'
complete -c docker-network-create -s d --description '.'
complete -c docker-network-create -s o -l opt --description '.'
complete -c docker-network-create -l subnet --description '.'

