# docker-history
# Autogenerated from man page /usr/share/man/man1/docker-history.1.gz
# using Deroffing man parser
complete -c docker-history -l help --description '  Print usage statement.'
complete -c docker-history -s H -l human --description '    Print sizes and dates in human readable format.'
complete -c docker-history -l no-trunc --description '   Don\'t truncate output.  The default is false.'
complete -c docker-history -s q -l quiet --description '   Only show numeric IDs.  The default is false.'

