# docker-login
# Autogenerated from man page /usr/share/man/man1/docker-login.1.gz
# using Deroffing man parser
complete -c docker-login -s e -l email --description '   Email.'
complete -c docker-login -l help --description '  Print usage statement.'
complete -c docker-login -s p -l password --description '   Password.'
complete -c docker-login -s u -l username --description '   Username EXAMPLES Login to a registry on you… [See Man Page]'

