# docker-wait
# Autogenerated from man page /usr/share/man/man1/docker-wait.1.gz
# using Deroffing man parser
complete -c docker-wait -l help --description '  Print usage statement EXAMPLES $ docker run -… [See Man Page]'

