# docker-inspect
# Autogenerated from man page /usr/share/man/man1/docker-inspect.1.gz
# using Deroffing man parser
complete -c docker-inspect -l help --description '    Print usage statement.'
complete -c docker-inspect -s f -l format --description '    Format the output using the given Go template.'
complete -c docker-inspect -s s -l size --description '    Display total file sizes if the type is container.'
complete -c docker-inspect -l type --description '    Return JSON for specified type, permissible… [See Man Page]'

