# docker-search
# Autogenerated from man page /usr/share/man/man1/docker-search.1.gz
# using Deroffing man parser
complete -c docker-search -l automated --description '   Only show automated builds.  The default is false.'
complete -c docker-search -l help --description '  Print usage statement.'
complete -c docker-search -l no-trunc --description '   Don\'t truncate output.  The default is false.'
complete -c docker-search -s s -l stars --description '   Only displays with at least X stars.  The default is zero.'

