# docker-volume-rm
# Autogenerated from man page /usr/share/man/man1/docker-volume-rm.1.gz
# using Deroffing man parser
complete -c docker-volume-rm -l help --description '  Print usage statement HISTORY.'

