# docker-stats
# Autogenerated from man page /usr/share/man/man1/docker-stats.1.gz
# using Deroffing man parser
complete -c docker-stats -l help --description '  Print usage statement.'
complete -c docker-stats -l no-stream --description '  Disable streaming stats and only pull the fir… [See Man Page]'

