# docker-events
# Autogenerated from man page /usr/share/man/man1/docker-events.1.gz
# using Deroffing man parser
complete -c docker-events -l help --description '  Print usage statement.'
complete -c docker-events -s f -l filter --description '   Provide filter values (i. e. , \'event=stop\').'
complete -c docker-events -l since --description '   Show all events created since timestamp.'
complete -c docker-events -l until --description '   Stream events until this timestamp You can s… [See Man Page]'

