# docker-kill
# Autogenerated from man page /usr/share/man/man1/docker-kill.1.gz
# using Deroffing man parser
complete -c docker-kill -l help --description '  Print usage statement.'
complete -c docker-kill -s s -l signal --description '   Signal to send to the container HISTORY.'

