# docker-stop
# Autogenerated from man page /usr/share/man/man1/docker-stop.1.gz
# using Deroffing man parser
complete -c docker-stop -l help --description '  Print usage statement.'
complete -c docker-stop -s t -l time --description '  Number of seconds to wait for the container t… [See Man Page]'

