# docker-pull
# Autogenerated from man page /usr/share/man/man1/docker-pull.1.gz
# using Deroffing man parser
complete -c docker-pull -s a -l all-tags --description '   Download all tagged images in the repository.'
complete -c docker-pull -l help --description '  Print usage statement EXAMPLE Pull a reposito… [See Man Page]'

