# docker-rmi
# Autogenerated from man page /usr/share/man/man1/docker-rmi.1.gz
# using Deroffing man parser
complete -c docker-rmi -s f --description 'OPTIONS.'
complete -c docker-rmi -l force --description '   Force removal of the image.  The default is false.'
complete -c docker-rmi -l help --description '  Print usage statement.'
complete -c docker-rmi -l no-prune --description '   Do not delete untagged parents.  The default is false.'

