# docker-import
# Autogenerated from man page /usr/share/man/man1/docker-import.1.gz
# using Deroffing man parser
complete -c docker-import -s c -l change --description '   Apply specified Dockerfile instructions whil… [See Man Page]'
complete -c docker-import -l help --description '  Print usage statement.'
complete -c docker-import -s m -l message --description '   Set commit message for imported image DESCRIPTION.'

