# docker-volume-create
# Autogenerated from man page /usr/share/man/man1/docker-volume-create.1.gz
# using Deroffing man parser
complete -c docker-volume-create -s d -l driver --description '  Specify volume driver name.'
complete -c docker-volume-create -l help --description '  Print usage statement.'
complete -c docker-volume-create -l name --description '  Specify volume name.'
complete -c docker-volume-create -s o -l opt --description '  Set driver specific options HISTORY.'

