# docker-attach
# Autogenerated from man page /usr/share/man/man1/docker-attach.1.gz
# using Deroffing man parser
complete -c docker-attach -l help --description '  Print usage statement.'
complete -c docker-attach -l no-stdin --description '   Do not attach STDIN.  The default is false.'
complete -c docker-attach -l sig-proxy --description '   Proxy all received signals to the process (n… [See Man Page]'

