# docker-save
# Autogenerated from man page /usr/share/man/man1/docker-save.1.gz
# using Deroffing man parser
complete -c docker-save -l help --description '  Print usage statement.'
complete -c docker-save -s o -l output --description '   Write to a file, instead of STDOUT EXAMPLES.'

