# docker-port
# Autogenerated from man page /usr/share/man/man1/docker-port.1.gz
# using Deroffing man parser
complete -c docker-port -l help --description '  Print usage statement EXAMPLES # docker ps CO… [See Man Page]'

