# docker-logs
# Autogenerated from man page /usr/share/man/man1/docker-logs.1.gz
# using Deroffing man parser
complete -c docker-logs -l help --description '  Print usage statement.'
complete -c docker-logs -s f -l follow --description '   Follow log output.  The default is false.'
complete -c docker-logs -l since --description '   Show logs since timestamp.'
complete -c docker-logs -s t -l timestamps --description '   Show timestamps.  The default is false.'
complete -c docker-logs -l tail --description '   Output the specified number of lines at the … [See Man Page]'

