# docker-commit
# Autogenerated from man page /usr/share/man/man1/docker-commit.1.gz
# using Deroffing man parser
complete -c docker-commit -s a -l author --description '   Author (e. g. , "John Hannibal Smith  [la]hannibal@a-team.'
complete -c docker-commit -s c -l change --description '   Apply specified Dockerfile instructions whil… [See Man Page]'
complete -c docker-commit -l help --description '  Print usage statement.'
complete -c docker-commit -s m -l message --description '   Commit message.'
complete -c docker-commit -s p -l pause --description '   Pause container during commit.  The default is true.'

