# docker-volume-inspect
# Autogenerated from man page /usr/share/man/man1/docker-volume-inspect.1.gz
# using Deroffing man parser
complete -c docker-volume-inspect -s f -l format --description '  Format the output using the given go template.'
complete -c docker-volume-inspect -l help --description '  Print usage statement HISTORY.'

