# docker-start
# Autogenerated from man page /usr/share/man/man1/docker-start.1.gz
# using Deroffing man parser
complete -c docker-start -s a -l attach --description '   Attach container\'s STDOUT and STDERR and for… [See Man Page]'
complete -c docker-start -l help --description '  Print usage statement.'
complete -c docker-start -s i -l interactive --description '   Attach container\'s STDIN.  The default is false.  See also.'

