# docker-rm
# Autogenerated from man page /usr/share/man/man1/docker-rm.1.gz
# using Deroffing man parser
complete -c docker-rm -l help --description '  Print usage statement.'
complete -c docker-rm -s f -l force --description '   Force the removal of a running container (uses SIGKILL).'
complete -c docker-rm -s l -l link --description '   Remove the specified link and not the underlying container.'
complete -c docker-rm -s v -l volumes --description '   Remove the volumes associated with the container.'

