# docker-exec
# Autogenerated from man page /usr/share/man/man1/docker-exec.1.gz
# using Deroffing man parser
complete -c docker-exec -s d -l detach --description '   Detached mode: run command in the background.'
complete -c docker-exec -l help --description '  Print usage statement.'
complete -c docker-exec -s i -l interactive --description '   Keep STDIN open even if not attached.  The default is false.'
complete -c docker-exec -l privileged --description '   Give the process extended  [la]http://man7.'
complete -c docker-exec -s t -l tty --description '   Allocate a pseudo-TTY.  The default is false.'
complete -c docker-exec -s u -l user --description '   Sets the username or UID used and optionally… [See Man Page]'

