# docker-build
# Autogenerated from man page /usr/share/man/man1/docker-build.1.gz
# using Deroffing man parser
complete -c docker-build -s f -l file --description '   Path to the Dockerfile to use.'
complete -c docker-build -l build-arg --description '   name and value of a buildarg.'
complete -c docker-build -l force-rm --description '   Always remove intermediate containers, even … [See Man Page]'
complete -c docker-build -l no-cache --description '   Do not use cache when building the image.'
complete -c docker-build -l help --description '  Print usage statement.'
complete -c docker-build -l pull --description '   Always attempt to pull a newer version of the image.'
complete -c docker-build -s q -l quiet --description '   Suppress the verbose output generated by the containers.'
complete -c docker-build -l rm --description '   Remove intermediate containers after a successful build.'
complete -c docker-build -s t -l tag --description '   Repository name (and optionally a tag) to be… [See Man Page]'
complete -c docker-build -s m -l memory --description '  Memory limit.'
complete -c docker-build -l memory-swap --description '  Total memory (memory + swap), \'-1\' to disable swap.'
complete -c docker-build -l cpu-shares --description '  CPU shares (relative weight).'
complete -c docker-build -l cpu-period --description '  Limit the CPU CFS (Completely Fair Scheduler) period.'
complete -c docker-build -l cpu-quota --description '  Limit the CPU CFS (Completely Fair Scheduler) quota.'
complete -c docker-build -l cpuset-cpus --description '  CPUs in which to allow execution (0-3, 0,1).'
complete -c docker-build -l cpuset-mems --description '  Memory nodes (MEMs) in which to allow execution (0-3, 0,1).'
complete -c docker-build -l cgroup-parent --description '  Path to cgroups under which the container\'s c… [See Man Page]'
complete -c docker-build -l ulimit --description '  Ulimit options For more information about uli… [See Man Page]'

