# docker-info
# Autogenerated from man page /usr/share/man/man1/docker-info.1.gz
# using Deroffing man parser
complete -c docker-info -l help --description '  Print usage statement EXAMPLES Display Docker… [See Man Page]'

