# docker-ps
# Autogenerated from man page /usr/share/man/man1/docker-ps.1.gz
# using Deroffing man parser
complete -c docker-ps -s a -l all --description '   Show all containers.'
complete -c docker-ps -l before --description '   Show only containers created before Id or Na… [See Man Page]'
complete -c docker-ps -s f -l filter --description '   Provide filter values.'
complete -c docker-ps -l format --description '   Pretty-print containers using a Go template.'
complete -c docker-ps -l help --description '  Print usage statement.'
complete -c docker-ps -s l -l latest --description '   Show only the latest created container, incl… [See Man Page]'
complete -c docker-ps -s n -s 1 --description '   Show n last created containers, include non-running ones.'
complete -c docker-ps -l no-trunc --description '   Don\'t truncate output.  The default is false.'
complete -c docker-ps -s q -l quiet --description '   Only display numeric IDs.  The default is false.'
complete -c docker-ps -s s -l size --description '   Display total file sizes.  The default is false.'
complete -c docker-ps -l since --description '   Show only containers created since Id or Nam… [See Man Page]'

