# docker-tag
# Autogenerated from man page /usr/share/man/man1/docker-tag.1.gz
# using Deroffing man parser
complete -c docker-tag -s f -l force --description '   When set to true, force the alias.  The default is false.'
complete -c docker-tag -l help --description '   Print usage statement.'

