# editmap
# Autogenerated from man page /usr/share/man/man8/editmap.8.gz
# using Deroffing man parser
complete -c editmap -s C --description 'Use the specified  sendmail configuration file … [See Man Page]'
complete -c editmap -s N --description 'Include the null byte that terminates strings i… [See Man Page]'
complete -c editmap -s f --description 'Normally all upper case letters in the key are … [See Man Page]'
complete -c editmap -s q --description 'Query the map for the specified key.'
complete -c editmap -s u --description 'Update the record for  key with  value or inser… [See Man Page]'
complete -c editmap -s x --description 'Deletes the specific key from the map.'

