# erb2
# Autogenerated from man page /usr/share/man/man1/erb2.1.1.gz
# using Darwin man parser
complete -c erb2 -l version --description 'Prints the version of erb2.  Pp.'
complete -c erb2 -s E --description '.'
complete -c erb2 -l encoding --description 'Specifies the default value(s) for external enc… [See Man Page]'
complete -c erb2 -s P --description 'Evaluates lines starting with "%" as Ruby code … [See Man Page]'
complete -c erb2 -s S --description 'Specifies the safe level in which eRuby script will run.  Pp.'
complete -c erb2 -s T --description 'Specifies trim mode (default 0).'
complete -c erb2 -s U --description 'can be one of Sets the default value for intern… [See Man Page]'
complete -c erb2 -s d --description '.'
complete -c erb2 -l debug --description 'Turns on debug mode.  "$DEBUG" will be set to true.  Pp.'
complete -c erb2 -s h --description '.'
complete -c erb2 -l help --description 'Prints a summary of the options.  Pp.'
complete -c erb2 -s n --description 'Used with x.'
complete -c erb2 -s v --description 'Enables verbose mode.  "$VERBOSE" will be set to true.  Pp.'
complete -c erb2 -s x --description 'Converts the eRuby script into Ruby script and … [See Man Page]'

