# errno
# Autogenerated from man page /usr/share/man/man1/errno.1.gz
# using Deroffing man parser
complete -c errno -s l -l list --description 'List all errno values.'
complete -c errno -s s -l search --description 'Search for errors whose description contains al… [See Man Page]'
complete -c errno -s S -l search-all-locales --description 'Like --search, but searches all installed locales.'

