# evolution
# Autogenerated from man page /usr/share/man/man1/evolution.1.gz
# using Deroffing man parser
complete -c evolution -s '?' -l help --description 'Show a help message listing all the options and their meanings.'
complete -c evolution -s c -l component --description 'Start Evolution by activating the desired component.'
complete -c evolution -l offline --description 'Start in offline mode.'
complete -c evolution -l online --description 'Start in online mode.'
complete -c evolution -l force-online --description 'Ignore network availability.'
complete -c evolution -l express --description 'Start in "express" mode.'
complete -c evolution -l force-shutdown --description 'Forcibly shut down all Evolution components.'
complete -c evolution -l debug --description 'RI "Send the debugging output of all components to " FILE ". ".'
complete -c evolution -l disable-eplugin --description 'Disable loading of any plugins.'
complete -c evolution -l disable-preview --description 'Disable preview pane of Mail, Contacts and Tasks.'
complete -c evolution -s i -l import --description 'Import URIs or file names given as rest of arguments.'
complete -c evolution -s q -l quit --description 'Request a running Evolution process to quit.'
complete -c evolution -l display --description 'X display to use.'
complete -c evolution -l clutter-display --description 'X display to use.'
complete -c evolution -l screen --description 'X screen to use.'

