# expn
# Autogenerated from man page /usr/share/man/man1/expn.1.gz
# using Deroffing man parser
complete -c expn -o aa --description 'flag, only expansions that result in legal addresses are used.'
complete -c expn -s a --description 'address, flag specifies that a few illegal addr… [See Man Page]'
complete -c expn -s 1 --description 'option.   For each .'
complete -c expn -o 111 --description 'will traverse no more than three levels deep.'
complete -c expn -s v --description 'verbose, flag will cause  expn  to show each ad… [See Man Page]'
complete -c expn -s w --description 'watch, flag will cause expn to show you its con… [See Man Page]'
complete -c expn -s d --description 'debug, flag will expose many of the inner worki… [See Man Page]'

