# ffmpegthumbnailer
# Autogenerated from man page /usr/share/man/man1/ffmpegthumbnailer.1.gz
# using Deroffing man parser
complete -c ffmpegthumbnailer -o 'i<s>' --description ': input file.'
complete -c ffmpegthumbnailer -o 'o<s>' --description ': output file.'
complete -c ffmpegthumbnailer -o 's<n>' --description ': thumbnail size (use 0 for original size) (default: 128).'
complete -c ffmpegthumbnailer -o 'q<n>' --description ': image quality (0 = bad, 10 = best) (default: … [See Man Page]'
complete -c ffmpegthumbnailer -o 'c<s>' --description ': override image format (jpeg or png) (default:… [See Man Page]'
complete -c ffmpegthumbnailer -o 't<n' --description ': time to seek to (percentage or absolute time … [See Man Page]'
complete -c ffmpegthumbnailer -s a --description ': ignore aspect ratio and generate square thumbnail.'
complete -c ffmpegthumbnailer -s f --description ': create a movie strip overlay.'
complete -c ffmpegthumbnailer -s h --description ': display this help AUTHOR Written by Dirk Vanden Boer.'

