# galculator
# Autogenerated from man page /usr/share/man/man1/galculator.1.gz
# using Deroffing man parser
complete -c galculator -s h -l help --description 'Show summary of options.'
complete -c galculator -s v -l version --description 'Show version of program.'

