# gdm-control
# Autogenerated from man page /usr/share/man/man1/gdm-control.1.gz
# using Type1
complete -c gdm-control -l help --description 'Display some help and exit.'
complete -c gdm-control -l none --description 'Do nothing special when the current session ends.'
complete -c gdm-control -l shutdown --description 'Shutdown the computer when the current session ends.'
complete -c gdm-control -l reboot --description 'eboot the computer when the current session ends.'
complete -c gdm-control -l suspend --description 'Suspend the computer when the current session ends.'

