# gdmflexiserver
# Autogenerated from man page /usr/share/man/man1/gdmflexiserver.1.gz
# using Type1
complete -c gdmflexiserver -s d -l debug --description 'Debugging output.'
complete -c gdmflexiserver -l version --description 'Version of this application.'

