# geany
# Autogenerated from man page /usr/share/man/man1/geany.1.gz
# using Type1
complete -c geany -l column --description 'Set initial column number for the first opened … [See Man Page]'
complete -c geany -s c -l config --description 'Use an alternate configuration directory.'
complete -c geany -l ft-names --description 'Print a list of Geany\'s internal filetype names… [See Man Page]'
complete -c geany -s g -l generate-tags --description 'Generate a global tags file (see documentation).'
complete -c geany -s P -l no-preprocessing --description 'Don\'t preprocess C/C++ files when generating tags.'
complete -c geany -s i -l new-instance --description 'Don\'t open files in a running instance, force o… [See Man Page]'
complete -c geany -s l -l line --description 'Set initial line number for the first opened file.'
complete -c geany -l list-documents --description 'Return a list of open documents in a running Geany instance.'
complete -c geany -s m -l no-msgwin --description 'Don\'t show the message window.'
complete -c geany -s n -l no-ctags --description 'Don\'t load symbol completion and call tip data.'
complete -c geany -s p -l no-plugins --description 'Don\'t load plugin support.'
complete -c geany -l print-prefix --description 'Print installation prefix, the data directory, … [See Man Page]'
complete -c geany -s r -l read-only --description 'Open all files given on the command line in read-only mode.'
complete -c geany -s s -l no-session --description 'Don\'t load the previous session\'s files.'
complete -c geany -s t -l no-terminal --description 'Don\'t load terminal support.'
complete -c geany -l socket-file --description 'Use this socket filename for communication with… [See Man Page]'
complete -c geany -l vte-lib --description 'Specify explicitly the path including filename … [See Man Page]'
complete -c geany -s v -l verbose --description 'Be verbose (print useful status messages).'
complete -c geany -s V -l version --description 'Show version information and exit.'

