# genresscript
# Autogenerated from man page /usr/share/man/man1/genresscript.1.gz
# using Deroffing man parser
complete -c genresscript -l type --description 'X list resources of this type instead of group_icon.'
complete -c genresscript -l base --description 'X the default extraction name of all resources.'
complete -c genresscript -l sort --description 'X sort alphabetically instead of using order in binary.'
complete -c genresscript -l help --description 'X display this help and exit.'
complete -c genresscript -s t --description '.'
complete -c genresscript -s b --description '.'
complete -c genresscript -s s --description '.'
complete -c genresscript -l version --description '.'

