# gitg
# Autogenerated from man page /usr/share/man/man1/gitg.1.gz
# using Deroffing man parser
complete -c gitg -s c -l commit --description 'Open  gitg  in commit view.'
complete -c gitg -s '?' -l help --description 'Show the help message.'
complete -c gitg -l left-right --description '.'

