# gnome-do
# Autogenerated from man page /usr/share/man/man1/gnome-do.1.gz
# using Deroffing man parser
complete -c gnome-do -l debug --description 'Print verbose status information to the termina… [See Man Page]'

