# gnome-disks
# Autogenerated from man page /usr/share/man/man1/gnome-disks.1.gz
# using Deroffing man parser
complete -c gnome-disks -l block-device --description 'Switches to the Disks application and selects t… [See Man Page]'
complete -c gnome-disks -l format-device --description 'Shows the \\(lqFormat Volume\\(rq dialog for the … [See Man Page]'
complete -c gnome-disks -l restore-disk-image --description 'Shows the \\(lqRestore Disk Image\\(rq dialog for… [See Man Page]'
complete -c gnome-disks -l help --description 'Prints a short help text and exits.'

