# gnome-desktop-item-edit
# Autogenerated from man page /usr/share/man/man1/gnome-desktop-item-edit.1.gz
# using Type1
complete -c gnome-desktop-item-edit -l create-new --description 'Create new file in the given directory.'

