# gvfsd-fuse
# Autogenerated from man page /usr/share/man/man1/gvfsd-fuse.1.gz
# using Deroffing man parser
complete -c gvfsd-fuse -s d --description 'Enable fuse debug output.  This implies -f.'
complete -c gvfsd-fuse -s f --description 'Run in the foreground.'
complete -c gvfsd-fuse -s s --description 'Run single-threaded.'
complete -c gvfsd-fuse -s o --description 'Set a fuse-specific option.'
complete -c gvfsd-fuse -o 'f.' --description '.'

