# gvfs-rm
# Autogenerated from man page /usr/share/man/man1/gvfs-rm.1.gz
# using Deroffing man parser
complete -c gvfs-rm -s '?' -l help --description 'Prints a short help text and exits.'
complete -c gvfs-rm -l version --description 'Shows the version number and exits.'
complete -c gvfs-rm -s f -l force --description 'Ignore nonexistent and non-deletable files.'

