# gweather
# Autogenerated from man page /usr/share/man/man1/gweather.1.gz
# using Deroffing man parser
complete -c gweather -l activate-goad-server --description '(Internal use only) GOAD server ID to activate.'

