# gyp
# Autogenerated from man page /usr/share/man/man1/gyp.1.gz
# using Deroffing man parser
complete -c gyp -o 'D<variable>' --description 'Provide a default value for the given variable.'
complete -c gyp -o 'f<format>[(' -l format --description 'Generate output in the formats listed.'
complete -c gyp -o 'I<path>' -l include --description 'Implicitly include the contents of the <path> f… [See Man Page]'
complete -c gyp -l depth --description 'For Chromium, the gyp "depth" variable should a… [See Man Page]'
complete -c gyp -o 'd<debug' -l debug --description 'Turn on debugging output.'
complete -c gyp -o 'S<suffix>' -l suffix --description 'Insert the specified string in the names of gen… [See Man Page]'
complete -c gyp -o 'G<flag>' --description 'Set a "generator flag", which is an option spec… [See Man Page]'
complete -c gyp -l generator-output --description 'Write the generated build files under the <dir>… [See Man Page]'
complete -c gyp -l ignore-environment --description 'Do not read options from environment variables.'
complete -c gyp -l check --description 'Take extra time to verify the syntax of each build_file.'
complete -c gyp -l parallel --description 'Use multiprocessing for speed (experimental).'
complete -c gyp -l toplevel-dir --description 'Directory to use as the root of the source tree.'
complete -c gyp -l build --description 'Configuration for build after project generation.'
complete -c gyp -l no-circular-check --description 'Disable the check for circular relationships between .'
complete -c gyp -s D --description '.'
complete -c gyp -s G --description '.'

