# i3-with-shmlog
# Autogenerated from man page /usr/share/man/man1/i3-with-shmlog.1.gz
# using Deroffing man parser
complete -c i3-with-shmlog -s a --description 'Disables autostart.'
complete -c i3-with-shmlog -s c --description 'Specifies an alternate configuration file path.'
complete -c i3-with-shmlog -s C --description 'Check the configuration file for validity and exit.'
complete -c i3-with-shmlog -s d --description 'Enables debug logging.'
complete -c i3-with-shmlog -s v --description 'Display version number (and date of the last commit).'
complete -c i3-with-shmlog -s V --description 'Be verbose.'
complete -c i3-with-shmlog -l force-xinerama --description 'Use Xinerama instead of RandR.'
complete -c i3-with-shmlog -l get-socketpath --description 'Retrieve the i3 IPC socket path from X11, print it, then exit.'
complete -c i3-with-shmlog -l shmlog-size --description 'Limits the size of the i3 SHM log to <limit> bytes.'

