# i386
# Autogenerated from man page /usr/share/man/man8/i386.8.gz
# using Deroffing man parser
complete -c i386 -l list --description 'List the architectures that can be set.'
complete -c i386 -l 'uname-2.6' --description 'Causes the program to see a kernel version numb… [See Man Page]'
complete -c i386 -s v -l verbose --description 'Be verbose.'
complete -c i386 -s 3 -l 3gb --description 'Specifies that processes should use a maximum o… [See Man Page]'
complete -c i386 -l 4gb --description 'Ignored (for backward compatibility only).'
complete -c i386 -s B -l 32bit --description 'Turns on ADDR_LIMIT_32BIT.'
complete -c i386 -s F -l fdpic-funcptrs --description 'Userspace function pointers point to descriptor… [See Man Page]'
complete -c i386 -s I -l short-inode --description 'Turns on SHORT_INODE.'
complete -c i386 -s L -l addr-compat-layout --description 'Changes the way virtual memory is allocated (tu… [See Man Page]'
complete -c i386 -s R -l addr-no-randomize --description 'Disables randomization of the virtual address s… [See Man Page]'
complete -c i386 -s S -l whole-seconds --description 'Turns on WHOLE_SECONDS.'
complete -c i386 -s T -l sticky-timeouts --description 'Turns on STICKY_TIMEOUTS.'
complete -c i386 -s X -l read-implies-exec --description 'Turns on READ_IMPLIES_EXEC.'
complete -c i386 -s Z -l mmap-page-zero --description 'Turns on MMAP_PAGE_ZERO.'
complete -c i386 -s V -l version --description 'Display version information and exit.'
complete -c i386 -s h -l help --description 'Display help text and exit.'

