# im-config
# Autogenerated from man page /usr/share/man/man8/im-config.8.gz
# using Deroffing man parser
complete -c im-config -s a --description 'List all; force to list all possible input meth… [See Man Page]'
complete -c im-config -s c --description 'Use console dialogue.'
complete -c im-config -s x --description 'Use X dialogue with zenity.'
complete -c im-config -s s --description 'No action; perform a simulation of events that … [See Man Page]'
complete -c im-config -s l --description 'List all available input method configuration s… [See Man Page]'
complete -c im-config -s m --description 'List configuration values to STDOUT: . RS 12 .'
complete -c im-config -s n --description '<input method name>  Set input method to <input method name>.'
complete -c im-config -s o --description '<input method name>.'

