# invgeod
# Autogenerated from man page /usr/share/man/man1/invgeod.1.gz
# using Deroffing man parser
complete -c invgeod -s I --description 'Specifies that the inverse geodesic computation… [See Man Page]'
complete -c invgeod -s a --description 'Latitude and longitudes of the initial and term… [See Man Page]'
complete -c invgeod -s t --description 'A specifies a character employed as the first c… [See Man Page]'
complete -c invgeod -o le --description 'Gives a listing of all the ellipsoids that may … [See Man Page]'
complete -c invgeod -o lu --description 'Gives a listing of all the units that may be se… [See Man Page]'
complete -c invgeod -o '[f' --description 'Format is a  printf format string to control th… [See Man Page]'
complete -c invgeod -o '[w' --description 'N is the number of significant fractional digit… [See Man Page]'
complete -c invgeod -o w3 --description 'is assumed).  When.'
complete -c invgeod -s W --description 'is employed the fields will be constant width w… [See Man Page]'
complete -c invgeod -s p --description 'This option causes the azimuthal values to be o… [See Man Page]'
complete -c invgeod -s f --description 'switch is not employed) to 0.'

