# ip6tables-apply
# Autogenerated from man page /usr/share/man/man8/ip6tables-apply.8.gz
# using Deroffing man parser
complete -c ip6tables-apply -s t -l timeout --description 'Sets the timeout in seconds after which the scr… [See Man Page]'
complete -c ip6tables-apply -s w -l write --description 'Specify the savefile where successfully applied… [See Man Page]'
complete -c ip6tables-apply -s c -l command --description 'Run command runcmd to configure iptables instea… [See Man Page]'
complete -c ip6tables-apply -s h -l help --description 'Display usage information.'
complete -c ip6tables-apply -s V -l version --description 'Display version information.  SEE ALSO.'

