# irqbalance
# Autogenerated from man page /usr/share/man/man1/irqbalance.1.gz
# using Deroffing man parser
complete -c irqbalance -l oneshot --description 'Causes irqbalance to be run once, after which the daemon exits.'
complete -c irqbalance -l debug --description 'Causes irqbalance to print extra debug information.'
complete -c irqbalance -l foreground --description 'Causes irqbalance to run in the foreground (without --debug).'
complete -c irqbalance -l hintpolicy --description 'Set the policy for how irq kernel affinity hinting is treated.'
complete -c irqbalance -l powerthresh --description 'Set the threshold at which we attempt to move a… [See Man Page]'
complete -c irqbalance -l banirq --description 'Add the specified irq to the set of banned irqs.'
complete -c irqbalance -l policyscript --description 'When specified, the referenced script will exec… [See Man Page]'
complete -c irqbalance -l pid --description 'Have irqbalance write its process id to the specified file.'

