# isutf8
# Autogenerated from man page /usr/share/man/man1/isutf8.1.gz
# using Deroffing man parser
complete -c isutf8 -s h -l help --description 'Print out a help summary.'
complete -c isutf8 -s q -l quiet --description 'Don\\*(Aqt print messages telling which files ar… [See Man Page]'

