# lckdo
# Autogenerated from man page /usr/share/man/man1/lckdo.1.gz
# using Deroffing man parser
complete -c lckdo -s w --description 'If the lock is already held by another process,… [See Man Page]'
complete -c lckdo -s W --description 'The same as -w but wait not more than sec seconds.'
complete -c lckdo -s e --description 'Execute the program directly without forking an… [See Man Page]'
complete -c lckdo -s E --description 'Set the file descriptor number to keep open whe… [See Man Page]'
complete -c lckdo -s n --description 'Do not create the lock file if it does not exist.'
complete -c lckdo -s q --description 'Produce no output if lock is already held.'
complete -c lckdo -s s --description 'Lock in shared (read) mode.'
complete -c lckdo -s x --description 'Lock in exclusive (write) mode (default).'
complete -c lckdo -s t --description 'Test for lock existence.'

