# libvirt-migrate-qemu-disks
# Autogenerated from man page /usr/share/man/man1/libvirt-migrate-qemu-disks.1.gz
# using Deroffing man parser
complete -c libvirt-migrate-qemu-disks -s h -l help --description 'show help message and exit.'
complete -c libvirt-migrate-qemu-disks -s a --description 'probe all domains and migrate if necessary.'
complete -c libvirt-migrate-qemu-disks -s c --description 'connection URI to use.'
complete -c libvirt-migrate-qemu-disks -s t --description 'migrate specified domains from raw to disk format TYPE.'
complete -c libvirt-migrate-qemu-disks -s d --description 'debug output.'

