# libvirt-migrate-qemu-machinetype
# Autogenerated from man page /usr/share/man/man1/libvirt-migrate-qemu-machinetype.1.gz
# using Deroffing man parser
complete -c libvirt-migrate-qemu-machinetype -s h -l help --description 'show help message and exit.'
complete -c libvirt-migrate-qemu-machinetype -s a --description 'probe all domains and migrate if necessary.'
complete -c libvirt-migrate-qemu-machinetype -s c --description 'connection URI to use.'
complete -c libvirt-migrate-qemu-machinetype -s o --description 'migrate specified domains from machine type TYPE (default pc-0.'
complete -c libvirt-migrate-qemu-machinetype -s t --description 'migrate specified domains to machine type TYPE (default pc-1.'
complete -c libvirt-migrate-qemu-machinetype -s d --description 'debug output.'

