# llc-3
# Autogenerated from man page /usr/share/man/man1/llc-3.6.1.gz
# using Deroffing man parser
complete -c llc-3 -o help --description 'Print a summary of command line options. UNINDENT NDENT 0. 0.'
complete -c llc-3 -s O --description 'Generate code at different optimization levels.'
complete -c llc-3 -o mtriple --description 'Override the target triple specified in the inp… [See Man Page]'
complete -c llc-3 -o march --description 'Specify the architecture for which to generate … [See Man Page]'
complete -c llc-3 -o mcpu --description 'Specify a specific chip in the current architec… [See Man Page]'
complete -c llc-3 -o filetype --description 'Specify what kind of output llc should generated.'
complete -c llc-3 -o mattr -o a3 --description 'Override or control specific attributes of the … [See Man Page]'
complete -c llc-3 -l disable-fp-elim --description 'Disable frame pointer elimination optimization.'
complete -c llc-3 -l disable-excess-fp-precision --description 'Disable optimizations that may produce excess p… [See Man Page]'
complete -c llc-3 -l enable-no-infs-fp-math --description 'Enable optimizations that assume no Inf values.'
complete -c llc-3 -l enable-no-nans-fp-math --description 'Enable optimizations that assume no NAN values.'
complete -c llc-3 -l enable-unsafe-fp-math --description 'Enable optimizations that make unsafe assumptio… [See Man Page]'
complete -c llc-3 -l stats --description 'Print statistics recorded by code-generation passes.'
complete -c llc-3 -l time-passes --description 'Record the amount of time needed for each pass … [See Man Page]'
complete -c llc-3 -l load --description 'Dynamically load dso_path (a path to a dynamica… [See Man Page]'
complete -c llc-3 -l print-machineinstrs --description 'Print generated machine code between compilatio… [See Man Page]'
complete -c llc-3 -l regalloc --description 'Specify the register allocator to use.'
complete -c llc-3 -l spiller --description 'Specify the spiller to use for register allocat… [See Man Page]'
complete -c llc-3 -o O0 -o O1 -o O2 -o O3 --description 'clang.'
complete -c llc-3 -l x86-asm-syntax --description 'Specify whether to emit assembly code in AT&T s… [See Man Page]'

