# llvm-readobj-3
# Autogenerated from man page /usr/share/man/man1/llvm-readobj-3.6.1.gz
# using Deroffing man parser
complete -c llvm-readobj-3 -o help --description 'Print a summary of command line options. UNINDENT NDENT 0. 0.'
complete -c llvm-readobj-3 -o version --description 'Display the version of this program . UNINDENT NDENT 0. 0.'
complete -c llvm-readobj-3 -o file-headers -s h --description 'Display file headers. UNINDENT NDENT 0. 0.'
complete -c llvm-readobj-3 -o sections -s s --description 'Display all sections. UNINDENT NDENT 0. 0.'
complete -c llvm-readobj-3 -o section-data -o sd --description 'When used with -sections, display section data … [See Man Page]'
complete -c llvm-readobj-3 -o section-relocations -o sr --description 'When used with -sections, display relocations f… [See Man Page]'
complete -c llvm-readobj-3 -o section-symbols -o st --description 'When used with -sections, display symbols for e… [See Man Page]'
complete -c llvm-readobj-3 -o relocations -s r --description 'Display the relocation entries in the file. UNINDENT NDENT 0.'
complete -c llvm-readobj-3 -o symbols -s t --description 'Display the symbol table. UNINDENT NDENT 0. 0.'
complete -c llvm-readobj-3 -o dyn-symbols --description 'Display the dynamic symbol table (only for ELF object files).'
complete -c llvm-readobj-3 -o unwind -s u --description 'Display unwind information. UNINDENT NDENT 0. 0.'
complete -c llvm-readobj-3 -o expand-relocs --description 'When used with -relocations, display each reloc… [See Man Page]'
complete -c llvm-readobj-3 -o dynamic-table --description 'Display the ELF .'
complete -c llvm-readobj-3 -o needed-libs --description 'Display the needed libraries (only for ELF object files).'
complete -c llvm-readobj-3 -o program-headers --description 'Display the ELF program headers (only for ELF object files).'

