# llvm-cov-3
# Autogenerated from man page /usr/share/man/man1/llvm-cov-3.6.1.gz
# using Deroffing man parser
complete -c llvm-cov-3 -s a -l all-blocks --description 'Display all basic blocks.'
complete -c llvm-cov-3 -s b -l branch-probabilities --description 'Display conditional branch probabilities and a … [See Man Page]'
complete -c llvm-cov-3 -s c -l branch-counts --description 'Display branch counts instead of probabilities (requires -b).'
complete -c llvm-cov-3 -s f -l function-summaries --description 'Show a summary of coverage for each function in… [See Man Page]'
complete -c llvm-cov-3 -l help --description 'Display available options (--help-hidden for more).'
complete -c llvm-cov-3 -s l -l long-file-names --description 'For coverage output of files included from the … [See Man Page]'
complete -c llvm-cov-3 -s n -l no-output --description 'Do not output any . gcov files.'
complete -c llvm-cov-3 -s o -l object-directory -l object-file --description 'Find objects in DIR or based on FILE\\(aqs path.'
complete -c llvm-cov-3 -s p -l preserve-paths --description 'Preserve path components when naming the coverage output files.'
complete -c llvm-cov-3 -s u -l unconditional-branches --description 'Include unconditional branches in the output fo… [See Man Page]'
complete -c llvm-cov-3 -o fprofile-arcs -o ftest-coverage --description 'instrumentation.'
complete -c llvm-cov-3 -o version --description 'Display the version of llvm-cov.'

