# llvm-profdata-3
# Autogenerated from man page /usr/share/man/man1/llvm-profdata-3.6.1.gz
# using Deroffing man parser
complete -c llvm-profdata-3 -o help --description 'Print a summary of command line options.'
complete -c llvm-profdata-3 -o output -s o --description 'Specify the output file name.'
complete -c llvm-profdata-3 -o all-functions --description 'Print details for every function.'
complete -c llvm-profdata-3 -o counts --description 'Print the counter values for the displayed functions.'
complete -c llvm-profdata-3 -o function --description 'Print details for a function if the function\'s … [See Man Page]'

