# llvm-config-3
# Autogenerated from man page /usr/share/man/man1/llvm-config-3.6.1.gz
# using Deroffing man parser
complete -c llvm-config-3 -l version --description 'Print the version number of LLVM.'
complete -c llvm-config-3 -o help --description 'Print a summary of llvm-config arguments.'
complete -c llvm-config-3 -l prefix --description 'Print the installation prefix for LLVM.'
complete -c llvm-config-3 -l src-root --description 'Print the source root from which LLVM was built.'
complete -c llvm-config-3 -l obj-root --description 'Print the object root used to build LLVM.'
complete -c llvm-config-3 -l bindir --description 'Print the installation directory for LLVM binaries.'
complete -c llvm-config-3 -l includedir --description 'Print the installation directory for LLVM headers.'
complete -c llvm-config-3 -l libdir --description 'Print the installation directory for LLVM libraries.'
complete -c llvm-config-3 -l cxxflags --description 'Print the C++ compiler flags needed to use LLVM headers.'
complete -c llvm-config-3 -l ldflags --description 'Print the flags needed to link against LLVM libraries.'
complete -c llvm-config-3 -l libs --description 'Print all the libraries needed to link against … [See Man Page]'
complete -c llvm-config-3 -l libnames --description 'Similar to --libs, but prints the bare filename… [See Man Page]'
complete -c llvm-config-3 -l libfiles --description 'Similar to --libs, but print the full path to e… [See Man Page]'
complete -c llvm-config-3 -l components --description 'Print all valid component names.'
complete -c llvm-config-3 -l targets-built --description 'Print the component names for all targets suppo… [See Man Page]'
complete -c llvm-config-3 -l build-mode --description 'Print the build mode used when LLVM was built (e. g.'
complete -c llvm-config-3 -l 'components.' --description 'libraries.   Useful "virtual" components include:.'

