# llvm-dis-3
# Autogenerated from man page /usr/share/man/man1/llvm-dis-3.6.1.gz
# using Deroffing man parser
complete -c llvm-dis-3 -s o --description 'OPTIONS.'
complete -c llvm-dis-3 -s f --description 'Enable binary output on terminals.'
complete -c llvm-dis-3 -o help --description 'Print a summary of command line options.'

