# llvm-as-3
# Autogenerated from man page /usr/share/man/man1/llvm-as-3.6.1.gz
# using Deroffing man parser
complete -c llvm-as-3 -s f --description 'Enable binary output on terminals.'
complete -c llvm-as-3 -o help --description 'Print a summary of command line options.'
complete -c llvm-as-3 -s o --description 'Specify the output file name.'

