# locale
# Autogenerated from man page /usr/share/man/man1/locale.1.gz
# using Deroffing man parser
complete -c locale -s a -l all-locales --description 'Display a list of all available locales.'
complete -c locale -s m -l charmaps --description 'Display the available charmaps (character set d… [See Man Page]'
complete -c locale -s c -l category-name --description 'For a category name argument, write the name of… [See Man Page]'
complete -c locale -s k -l keyword-name --description 'For each keyword whose value is being displayed… [See Man Page]'
complete -c locale -s v -l verbose --description 'Display additional information for some command… [See Man Page]'
complete -c locale -s '?' -l help --description 'Display a summary of command-line options and a… [See Man Page]'
complete -c locale -l usage --description 'Display a short usage message and exit.'
complete -c locale -s V -l version --description 'Display the program version and exit.  FILES.'

