# logger
# Autogenerated from man page /usr/share/man/man1/logger.1.gz
# using Deroffing man parser
complete -c logger -s d -l udp --description 'Use datagram (UDP) only.'
complete -c logger -s h -l help --description 'Display help text and exit.'
complete -c logger -s i -l id --description 'Log the process ID of the logger process with each line.'
complete -c logger -s n -l server --description 'Write to the specified remote syslog  server in… [See Man Page]'
complete -c logger -s P -l port --description 'Use the specified R port .'
complete -c logger -s f -l file --description 'Log the contents of the specified R file .'
complete -c logger -s p -l priority --description 'Enter the message into the log with the specified R priority  .'
complete -c logger -l prio-prefix --description 'Look for a syslog prefix on every line read fro… [See Man Page]'
complete -c logger -s s -l stderr --description 'Output the message to standard error as well as… [See Man Page]'
complete -c logger -s T -l tcp --description 'Use stream (TCP) only.'
complete -c logger -s t -l tag --description 'Mark every line to be logged with the specified R tag .'
complete -c logger -s u -l socket --description 'Write to the specified  socket instead of to th… [See Man Page]'
complete -c logger -l journald --description 'Write systemd journal entry.'
complete -c logger -s V -l version --description 'Display version information and exit.'

