# lsw
# Autogenerated from man page /usr/share/man/man1/lsw.1.gz
# using Deroffing man parser
complete -c lsw -s l --description 'lsw lists each window\'s XID as well as its title.'
complete -c lsw -s v --description 'prints version information to stdout, then exits.'

