# lxpanel
# Autogenerated from man page /usr/share/man/man1/lxpanel.1.gz
# using Deroffing man parser
complete -c lxpanel -s h -l help --description 'Print help on the options.'
complete -c lxpanel -s v -l version --description 'Print the program version.'
complete -c lxpanel -l log --description 'Set the logging level in the range 0 (silent) t… [See Man Page]'
complete -c lxpanel -s p -l profile --description 'Set the profile to be loaded.'

