# lxsession-logout
# Autogenerated from man page /usr/share/man/man1/lxsession-logout.1.gz
# using Deroffing man parser
complete -c lxsession-logout -l prompt --description 'Customize the logout message.'
complete -c lxsession-logout -l banner --description 'Customize the logout logo.'
complete -c lxsession-logout -l side --description 'The position of the logo.'

