# lxshortcut
# Autogenerated from man page /usr/share/man/man1/lxshortcut.1.gz
# using Deroffing man parser
complete -c lxshortcut -s i -l input --description 'use input-file as source for editing, it may be… [See Man Page]'
complete -c lxshortcut -s o -l output --description 'write result into output-file SEE ALSO XDG Desk… [See Man Page]'

