# lxterminal
# Autogenerated from man page /usr/share/man/man1/lxterminal.1.gz
# using Deroffing man parser
complete -c lxterminal -s e -l command -l command --description 'This option specifies the program (and its comm… [See Man Page]'
complete -c lxterminal -l geometry --description 'Set the terminal\\*(Aqs size in characters and lines.'
complete -c lxterminal -s l -l loginshell --description 'Executes login shell.'
complete -c lxterminal -s t -l title -l tabs --description 'Set the terminal\\*(Aqs title.  Use comma for multiple tabs.'
complete -c lxterminal -l working-directory --description 'Set the terminal\\*(Aqs working directory.'

