# mail
# Autogenerated from man page /usr/share/man/man8/mail.local.8.gz
# using Deroffing man parser
complete -c mail -s b --description 'Return a permanent error instead of a temporary… [See Man Page]'
complete -c mail -s d --description 'Specify this is a delivery (for backward compatibility).'
complete -c mail -s D --description 'Specify the name of the mailbox database which … [See Man Page]'
complete -c mail -s f --description 'Specify the sender\'s name.'
complete -c mail -s l --description 'Turn on LMTP mode.'
complete -c mail -s r --description 'Specify the sender\'s name (for backward compatibility).'
complete -c mail -s h --description 'Store incoming mail in filename in the user\'s h… [See Man Page]'
complete -c mail -s H --description 'Select hashed mail directories.'
complete -c mail -s p --description 'Specify an alternate mail spool path.'
complete -c mail -s 7 --description 'Do not advertise 8BITMIME support in LMTP mode.'
complete -c mail -s n --description 'Specify that the domain part of recipient addre… [See Man Page]'

