# mailstats
# Autogenerated from man page /usr/share/man/man8/mailstats.8.gz
# using Deroffing man parser
complete -c mailstats -s C --description 'Read the specified file instead of the default … [See Man Page]'
complete -c mailstats -s c --description 'Try to use submit.'
complete -c mailstats -s f --description 'Read the specified statistics file instead of t… [See Man Page]'
complete -c mailstats -s P --description 'Output information in program-readable mode wit… [See Man Page]'
complete -c mailstats -s p --description 'Output information in program-readable mode and… [See Man Page]'
complete -c mailstats -s o --description 'Don\'t display the name of the mailer in the output.'

