# makemap
# Autogenerated from man page /usr/share/man/man8/makemap.8.gz
# using Deroffing man parser
complete -c makemap -s C --description 'Use the specified  sendmail configuration file … [See Man Page]'
complete -c makemap -s N --description 'Include the null byte that terminates strings  in the map.'
complete -c makemap -s c --description 'Use the specified hash and B-Tree cache size.'
complete -c makemap -s D --description 'Use to specify the character to use to indicate… [See Man Page]'
complete -c makemap -s d --description 'Allow duplicate keys in the map.'
complete -c makemap -s e --description 'Allow empty value (right hand side).'
complete -c makemap -s f --description 'Normally all upper case letters in the key  are… [See Man Page]'
complete -c makemap -s l --description 'List supported map types.'
complete -c makemap -s o --description 'Append to an old file.'
complete -c makemap -s r --description 'Allow replacement of existing keys.'
complete -c makemap -s s --description 'Ignore safety checks on maps being created.'
complete -c makemap -s t --description 'Use the specified delimiter instead of white sp… [See Man Page]'
complete -c makemap -s u --description 'dump (unmap) the content of the database to standard output.'
complete -c makemap -s v --description 'Verbosely print what it is doing.'

