# mcookie
# Autogenerated from man page /usr/share/man/man1/mcookie.1.gz
# using Deroffing man parser
complete -c mcookie -s f -l file --description 'Use additional file as a macig cookie random seed.'
complete -c mcookie -s m -l max-size --description 'Read form  FILE only  number of bytes.'
complete -c mcookie -s v -l verbose --description 'Inform where randomness originated, with amount… [See Man Page]'
complete -c mcookie -s V -l version --description 'Display version information and exit.'
complete -c mcookie -s h -l help --description 'Display help text and exit.'

