# mk-origtargz
# Autogenerated from man page /usr/share/man/man1/mk-origtargz.1.gz
# using Type1
complete -c mk-origtargz -l package --description 'Use package as the name of the Debian source pa… [See Man Page]'
complete -c mk-origtargz -s v -l version --description 'Use version as the version of the package.'
complete -c mk-origtargz -l exclude-file --description 'Remove files matching the given glob from the t… [See Man Page]'
complete -c mk-origtargz -l copyright-file --description 'Remove files matching the patterns found in fil… [See Man Page]'
complete -c mk-origtargz -l symlink --description 'Make the resulting file a symlink to the given original file.'
complete -c mk-origtargz -l copy --description 'Make the resulting file a copy of the original … [See Man Page]'
complete -c mk-origtargz -l rename --description 'Rename the original file.'
complete -c mk-origtargz -l repack --description 'If the given file is not compressed using the d… [See Man Page]'
complete -c mk-origtargz -s S -l repack-suffix --description 'If the file has to be modified, because of File… [See Man Page]'
complete -c mk-origtargz -l compression --description 'If --repack is used, or if the given file is a … [See Man Page]'

