# mkexfatfs
# Autogenerated from man page /usr/share/man/man8/mkexfatfs.8.gz
# using Deroffing man parser
complete -c mkexfatfs -s i --description 'A 32-bit hexadecimal number.'
complete -c mkexfatfs -s n --description 'Volume name (label), up to 15 characters.'
complete -c mkexfatfs -s p --description 'First sector of the partition starting from the… [See Man Page]'
complete -c mkexfatfs -s s --description 'Number of physical sectors per cluster (cluster… [See Man Page]'
complete -c mkexfatfs -s V --description 'Print version and copyright.'

