# mkfifo
# Autogenerated from man page /usr/share/man/man1/mkfifo.1.gz
# using Deroffing man parser
complete -c mkfifo -s m -l mode --description 'set file permission bits to MODE, not a=rw - umask.'
complete -c mkfifo -s Z --description 'set the SELinux security context to default type.'
complete -c mkfifo -l 'context[' --description 'like -Z, or if CTX is specified then set the SE… [See Man Page]'
complete -c mkfifo -l help --description 'display this help and exit.'
complete -c mkfifo -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

