# ModemManager
# Autogenerated from man page /usr/share/man/man8/ModemManager.8.gz
# using Deroffing man parser
complete -c ModemManager -l version --description 'Print the ModemManager software version and exit.'
complete -c ModemManager -l help --description 'Print ModemManager\'s available options and exit.'
complete -c ModemManager -l debug --description 'Runs ModemManager with "DEBUG" log level and wi… [See Man Page]'
complete -c ModemManager -l log-level --description 'Sets how much information ModemManager sends to… [See Man Page]'
complete -c ModemManager -l log-file --description 'Specify location of the file where ModemManager… [See Man Page]'
complete -c ModemManager -l timestamps --description 'Include absolute timestamps in the log output.'
complete -c ModemManager -l relative-timestamps --description 'Include timestamps, relative to the start time … [See Man Page]'

