# mysqlauditadmin
# Autogenerated from man page /usr/share/man/man1/mysqlauditadmin.1.gz
# using Deroffing man parser
complete -c mysqlauditadmin -l audit-log-name --description 'to the destination path specified by.'
complete -c mysqlauditadmin -l 'copy-to.' --description '.'
complete -c mysqlauditadmin -l remote-login --description 'option can be used to copy log files from a remote location.'
complete -c mysqlauditadmin -l value --description 'option.  Note The.'
complete -c mysqlauditadmin -l server --description 'option is also required to execute this command.  oc o 2. 3.'
complete -c mysqlauditadmin -l file-stats --description 'option, and the copy command.  oc o 2. 3.'
complete -c mysqlauditadmin -l copy-to --description '.'
complete -c mysqlauditadmin -l help --description '.'
complete -c mysqlauditadmin -l show-options --description '.'
complete -c mysqlauditadmin -l server1 --description '.'
complete -c mysqlauditadmin -l verbose -s v --description '.'
complete -c mysqlauditadmin -o vv --description '= more verbose,.'
complete -c mysqlauditadmin -o vvv --description '= debug.  oc o 2. 3.'
complete -c mysqlauditadmin -l version --description '.'

