# mysqlserverinfo
# Autogenerated from man page /usr/share/man/man1/mysqlserverinfo.1.gz
# using Deroffing man parser
complete -c mysqlserverinfo -l basedir --description '.'
complete -c mysqlserverinfo -l datadir --description '.'
complete -c mysqlserverinfo -l start --description 'options to prevent the utility from starting an… [See Man Page]'
complete -c mysqlserverinfo -l format --description 'option: oc o 2. 3.'
complete -c mysqlserverinfo -l no-headers --description 'option.'
complete -c mysqlserverinfo -l show-defaults --description 'option.'
complete -c mysqlserverinfo -l server --description 'option specifies.'
complete -c mysqlserverinfo -l show-servers --description 'option.'
complete -c mysqlserverinfo -l help --description '.'
complete -c mysqlserverinfo -o 'f<format>' --description '.'
complete -c mysqlserverinfo -s h --description '.'
complete -c mysqlserverinfo -l port-range --description '.'
complete -c mysqlserverinfo -s d --description '.'
complete -c mysqlserverinfo -s s --description '.'
complete -c mysqlserverinfo -l start-timeout --description '.'
complete -c mysqlserverinfo -l verbose -s v --description '.'
complete -c mysqlserverinfo -o vv --description '= more verbose,.'
complete -c mysqlserverinfo -o vvv --description '= debug.  oc o 2. 3.'
complete -c mysqlserverinfo -l version --description '.'

