# mysqlfrm
# Autogenerated from man page /usr/share/man/man1/mysqlfrm.1.gz
# using Deroffing man parser
complete -c mysqlfrm -l version --description 'show program\'s version number and exit . HP --help.'
complete -c mysqlfrm -l basedir --description 'the base directory for the server.'
complete -c mysqlfrm -l diagnostic --description 'read the frm files byte-by-byte to form the CREATE statement.'
complete -c mysqlfrm -l new-storage-engine --description 'change ENGINE clause to use this engine.'
complete -c mysqlfrm -l port --description 'Port to use for the spawned server.'
complete -c mysqlfrm -s s -l show-stats --description 'show file statistics and general table information.'
complete -c mysqlfrm -l server --description 'connection information for the server in the fo… [See Man Page]'
complete -c mysqlfrm -l user --description 'user account to launch spawned server.'
complete -c mysqlfrm -l start-timeout --description 'Number of seconds to wait for spawned server to start.'
complete -c mysqlfrm -s v -l verbose --description 'control how much information is displayed.  e. g.'
complete -c mysqlfrm -s q -l quiet --description 'turn off all messages for quiet execution.'
complete -c mysqlfrm -l verbosity --description 'output from the spawned server and repair any e… [See Man Page]'
complete -c mysqlfrm -l help --description '.'
complete -c mysqlfrm -l ---------- --description 'The mysqlfrm utility is designed as a recovery … [See Man Page]'
complete -c mysqlfrm -l ----------- --description '.'

