# mysqluserclone
# Autogenerated from man page /usr/share/man/man1/mysqluserclone.1.gz
# using Deroffing man parser
complete -c mysqluserclone -l list --description 'option.'
complete -c mysqluserclone -l format --description 'option: oc o 2. 3.'
complete -c mysqluserclone -l help --description '.'
complete -c mysqluserclone -l destination --description '.'
complete -c mysqluserclone -l dump -s d --description '.'
complete -c mysqluserclone -o 'f<list_format>' --description '.'
complete -c mysqluserclone -l force --description '.'
complete -c mysqluserclone -l include-global-privileges --description '.'
complete -c mysqluserclone -l quiet -s q --description '.'
complete -c mysqluserclone -l source --description '.'
complete -c mysqluserclone -l verbose -s v --description '.'
complete -c mysqluserclone -o vv --description '= more verbose,.'
complete -c mysqluserclone -o vvv --description '= debug.  oc o 2. 3.'
complete -c mysqluserclone -l version --description '.'

