# mysqldiff
# Autogenerated from man page /usr/share/man/man1/mysqldiff.1.gz
# using Deroffing man parser
complete -c mysqldiff -l server1 --description 'option.'
complete -c mysqldiff -l server2 --description 'option.'
complete -c mysqldiff -l difftype --description 'option to produce a listing that contains the a… [See Man Page]'
complete -c mysqldiff -l changes-for --description 'option controls the direction of the difference… [See Man Page]'
complete -c mysqldiff -l show-reverse --description 'option.'
complete -c mysqldiff -l force --description 'option to cause the utility to attempt to compa… [See Man Page]'
complete -c mysqldiff -l help --description '.'
complete -c mysqldiff -o 'd<difftype>' --description '.'
complete -c mysqldiff -l quiet -s q --description '.'
complete -c mysqldiff -l verbose -s v --description '.'
complete -c mysqldiff -o vv --description '= more verbose,.'
complete -c mysqldiff -o vvv --description '= debug.  oc o 2. 3.'
complete -c mysqldiff -l version --description '.'
complete -c mysqldiff -l width --description '.'

