# mysqlmetagrep
# Autogenerated from man page /usr/share/man/man1/mysqlmetagrep.1.gz
# using Deroffing man parser
complete -c mysqlmetagrep -l server --description 'option.  It produces output that displays the matching objects.'
complete -c mysqlmetagrep -l pattern --description 'option is given.  If the.'
complete -c mysqlmetagrep -l sql --description 'option to have the utility display the statemen… [See Man Page]'
complete -c mysqlmetagrep -l regexp --description 'option.'
complete -c mysqlmetagrep -l format --description 'option: oc o 2. 3.'
complete -c mysqlmetagrep -l help --description '.'
complete -c mysqlmetagrep -l body -s b --description '.'
complete -c mysqlmetagrep -l database --description '.'
complete -c mysqlmetagrep -o 'f<format>' --description '.'
complete -c mysqlmetagrep -l object-types -l search-objects --description '.'
complete -c mysqlmetagrep -s e --description '.'
complete -c mysqlmetagrep -l basic-regexp -s G --description '.'
complete -c mysqlmetagrep -l print-sql -s p --description '.'
complete -c mysqlmetagrep -l version --description '.'

