# mysqldiskusage
# Autogenerated from man page /usr/share/man/man1/mysqldiskusage.1.gz
# using Deroffing man parser
complete -c mysqldiskusage -l format --description 'option: oc o 2. 3.'
complete -c mysqldiskusage -l no-headers --description 'option.        OPTIONS.'
complete -c mysqldiskusage -l help --description '.'
complete -c mysqldiskusage -l all -s a --description '.'
complete -c mysqldiskusage -l binlog -s b --description '.'
complete -c mysqldiskusage -l empty -s m --description '.'
complete -c mysqldiskusage -o 'f<format>' --description '.'
complete -c mysqldiskusage -l innodb -s i --description '.'
complete -c mysqldiskusage -l logs -s l --description '.'
complete -c mysqldiskusage -s h --description '.'
complete -c mysqldiskusage -l quiet -s q --description '.'
complete -c mysqldiskusage -l relaylog -s r --description '.'
complete -c mysqldiskusage -l server --description '.'
complete -c mysqldiskusage -l verbose -s v --description '.'
complete -c mysqldiskusage -o vv --description '= more verbose,.'
complete -c mysqldiskusage -o vvv --description '= debug.  oc o 2. 3.'
complete -c mysqldiskusage -l version --description '.'

