# mysqlserverclone
# Autogenerated from man page /usr/share/man/man1/mysqlserverclone.1.gz
# using Deroffing man parser
complete -c mysqlserverclone -l new-data --description 'option, the utility shall issue an error.'
complete -c mysqlserverclone -l delete-data --description 'option to permit the utility to remove the fold… [See Man Page]'
complete -c mysqlserverclone -l help --description '.'
complete -c mysqlserverclone -l mysqld --description '.'
complete -c mysqlserverclone -l log-bin --description 'and.'
complete -c mysqlserverclone -l general-log-file --description '.'
complete -c mysqlserverclone -l new-id --description '.'
complete -c mysqlserverclone -l new-port --description '.'
complete -c mysqlserverclone -l quiet -s q --description '.'
complete -c mysqlserverclone -l root-password --description '.'
complete -c mysqlserverclone -l server --description '.'
complete -c mysqlserverclone -l start-timeout --description '.'
complete -c mysqlserverclone -l verbose -s v --description '.'
complete -c mysqlserverclone -o vv --description '= more verbose,.'
complete -c mysqlserverclone -o vvv --description '= debug.  oc o 2. 3.'
complete -c mysqlserverclone -l version --description '.'
complete -c mysqlserverclone -l write-command -o 'w<file_name>' --description '.'

