# mysqlrplcheck
# Autogenerated from man page /usr/share/man/man1/mysqlrplcheck.1.gz
# using Deroffing man parser
complete -c mysqlrplcheck -l verbose --description 'option to see additional information such as se… [See Man Page]'
complete -c mysqlrplcheck -l show-slave-status --description 'option.        OPTIONS.'
complete -c mysqlrplcheck -l help --description '.'
complete -c mysqlrplcheck -l master --description '.'
complete -c mysqlrplcheck -l master-info-file --description '.'
complete -c mysqlrplcheck -l quiet -s q --description '.'
complete -c mysqlrplcheck -s s --description '.'
complete -c mysqlrplcheck -l slave --description '.'
complete -c mysqlrplcheck -l suppress --description '.'
complete -c mysqlrplcheck -s v --description '.'
complete -c mysqlrplcheck -o vv --description '= more verbose,.'
complete -c mysqlrplcheck -o vvv --description '= debug.  oc o 2. 3.'
complete -c mysqlrplcheck -l version --description '.'
complete -c mysqlrplcheck -l width --description '.'
complete -c mysqlrplcheck -l ---------------------------------------------------------------------- --description 'Checking for binary logging on master          … [See Man Page]'

