# mysqlreplicate
# Autogenerated from man page /usr/share/man/man1/mysqlreplicate.1.gz
# using Deroffing man parser
complete -c mysqlreplicate -l pedantic --description 'option, which requires storage engines to be th… [See Man Page]'
complete -c mysqlreplicate -o vv --description 'option displays any discrepancies between the s… [See Man Page]'
complete -c mysqlreplicate -l start-from-beginning --description 'option.  oc o 2. 3.'
complete -c mysqlreplicate -l master-log-file --description 'option.  oc o 2. 3.'
complete -c mysqlreplicate -l master-log-pos --description 'options.'
complete -c mysqlreplicate -l help --description '.'
complete -c mysqlreplicate -l master --description '.'
complete -c mysqlreplicate -s p --description '.'
complete -c mysqlreplicate -l rpl-user --description '.'
complete -c mysqlreplicate -l slave --description '.'
complete -c mysqlreplicate -s b --description '.'
complete -c mysqlreplicate -l test-db --description '.'
complete -c mysqlreplicate -l verbose -s v --description '.'
complete -c mysqlreplicate -o vvv --description '= debug.  oc o 2. 3.'
complete -c mysqlreplicate -l version --description '.'

