# mysqluc
# Autogenerated from man page /usr/share/man/man1/mysqluc.1.gz
# using Deroffing man parser
complete -c mysqluc -l utildir --description 'is used to provide a path to the MySQL Utilitie… [See Man Page]'
complete -c mysqluc -l -------------------- -l ------------------------------------------------- --description 'help utilities          Display list of all uti… [See Man Page]'
complete -c mysqluc -l 'execute.' --description '.'
complete -c mysqluc -l version --description '.'
complete -c mysqluc -l help --description '.'
complete -c mysqluc -l verbose -s v --description '.'
complete -c mysqluc -o vv --description '= more verbose,.'
complete -c mysqluc -o vvv --description '= debug oc o 2. 3.'
complete -c mysqluc -l quiet --description '.'
complete -c mysqluc -l execute -s e --description '.'
complete -c mysqluc -l width --description '.'
complete -c mysqluc -l -------------- -l ------------------------------------------------------- --description 'mysqlindexcheck   check for duplicate or redund… [See Man Page]'
complete -c mysqluc -l ------ -l --------------------------------------------------------------- --description 'SERVER    root@host123 VAR_A     57 COPYRIGHT.'

