# mysqlindexcheck
# Autogenerated from man page /usr/share/man/man1/mysqlindexcheck.1.gz
# using Deroffing man parser
complete -c mysqlindexcheck -l show-drops --description 'option.  To examine the existing indexes, use the.'
complete -c mysqlindexcheck -l verbose --description 'option, which prints the equivalent CREATE INDE… [See Man Page]'
complete -c mysqlindexcheck -l best --description 'or.'
complete -c mysqlindexcheck -l worst --description 'option.'
complete -c mysqlindexcheck -l show-indexes --description '.'
complete -c mysqlindexcheck -l format --description 'option: oc o 2. 3.'
complete -c mysqlindexcheck -l help --description '.'
complete -c mysqlindexcheck -l 'best[' --description '.'
complete -c mysqlindexcheck -l stats --description 'is given, limit index statistics to the best N indexes.'
complete -c mysqlindexcheck -o 'f<index_format>' --description '.'
complete -c mysqlindexcheck -l 'stats.' --description 'grid, csv, tab, sql, and vertical.  The default is grid.'
complete -c mysqlindexcheck -l server --description '.'
complete -c mysqlindexcheck -s d --description '.'
complete -c mysqlindexcheck -s i --description '.'
complete -c mysqlindexcheck -l skip -s s --description '.'
complete -c mysqlindexcheck -s v --description '.'
complete -c mysqlindexcheck -o vv --description '= more verbose,.'
complete -c mysqlindexcheck -o vvv --description '= debug.  oc o 2. 3.'
complete -c mysqlindexcheck -l version --description '.'
complete -c mysqlindexcheck -l 'worst[' --description '.'

