# mysqlauditgrep
# Autogenerated from man page /usr/share/man/man1/mysqlauditgrep.1.gz
# using Deroffing man parser
complete -c mysqlauditgrep -l 'end-date)' --description '.'
complete -c mysqlauditgrep -l pattern --description 'supports two types of pattern matching: standar… [See Man Page]'
complete -c mysqlauditgrep -l format --description 'is passed in without search parameters, then al… [See Man Page]'
complete -c mysqlauditgrep -l file-stats --description 'option is not considered a search criteria, and… [See Man Page]'
complete -c mysqlauditgrep -l end-date --description '.'
complete -c mysqlauditgrep -l event-type --description '.'
complete -c mysqlauditgrep -s f --description '.'
complete -c mysqlauditgrep -l help --description '.'
complete -c mysqlauditgrep -s e --description '.'
complete -c mysqlauditgrep -l regexp --description 'option is set, then REGEXP patterns must be spe… [See Man Page]'
complete -c mysqlauditgrep -l query-type --description '.'
complete -c mysqlauditgrep -l basic-regexp -s G --description '.'
complete -c mysqlauditgrep -l start-date --description '.'
complete -c mysqlauditgrep -l status --description '.'
complete -c mysqlauditgrep -l users -s u --description '.'
complete -c mysqlauditgrep -l verbose -s v --description '.'
complete -c mysqlauditgrep -o vv --description '= more verbose,.'
complete -c mysqlauditgrep -o vvv --description '= debug.  oc o 2. 3.'
complete -c mysqlauditgrep -l version --description '.'

