# newusers
# Autogenerated from man page /usr/share/man/man8/newusers.8.gz
# using Deroffing man parser
complete -c newusers -s h -l help --description 'Display help message and exit.'
complete -c newusers -s r -l system --description 'Create a system account.'
complete -c newusers -s R -l root --description 'Apply changes in the CHROOT_DIR directory and u… [See Man Page]'

