# nginx
# Autogenerated from man page /usr/share/man/man1/nginx.1.gz
# using Deroffing man parser
complete -c nginx -s '?' -s h --description 'Show this help.'
complete -c nginx -s v --description 'Show version and exit.'
complete -c nginx -s V --description 'Show version and configure options then exit.'
complete -c nginx -s s --description 'Send signal to a master process: stop, quit, reopen, reload.'
complete -c nginx -s p --description 'Set prefix path.'
complete -c nginx -s g --description 'Set global directives out of configuration file.'
complete -c nginx -s c --description 'Specifies a particular configuration file for nginx to load.'
complete -c nginx -s t --description 'Tests nginx configuration and exit.'

