# nm-connection-editor
# Autogenerated from man page /usr/share/man/man1/nm-connection-editor.1.gz
# using Deroffing man parser
complete -c nm-connection-editor -s t -l type --description 'Type of connection to create or show.'
complete -c nm-connection-editor -s s -l show --description 'Expand or collapse the network list to highligh… [See Man Page]'
complete -c nm-connection-editor -s c -l create --description 'Create a new connection of the type given by --… [See Man Page]'
complete -c nm-connection-editor -s e -l edit --description 'Show the network connection edit window for the… [See Man Page]'

