# npm-install
# Autogenerated from man page /usr/share/man/man1/npm-install.1.gz
# using Deroffing man parser
complete -c npm-install -l save: --description '.'
complete -c npm-install -l save-dev: --description '.'
complete -c npm-install -l save-optional: --description '.'
complete -c npm-install -l save-exact: --description '.'

