# npm-uninstall
# Autogenerated from man page /usr/share/man/man1/npm-uninstall.1.gz
# using Deroffing man parser
complete -c npm-uninstall -l save: --description '.'
complete -c npm-uninstall -l save-dev: --description '.'
complete -c npm-uninstall -l save-optional: --description '.'

