# obconf
# Autogenerated from man page /usr/share/man/man1/obconf.1.gz
# using Deroffing man parser
complete -c obconf -l archive --description 'Create a theme archive from the given theme directory.'
complete -c obconf -l config-file --description 'Specify the path to the configuration file to use.'
complete -c obconf -l install --description 'Installs the given theme archive and selects it.'
complete -c obconf -l tab --description 'Display the tab number NUMBER.'
complete -c obconf -l version --description 'Displays information about the currently instal… [See Man Page]'

