# obxprop
# Autogenerated from man page /usr/share/man/man1/obxprop.1.gz
# using Type1
complete -c obxprop -l help --description 'Show a summary of the options available.'
complete -c obxprop -l display --description 'Specify the X display to use.'

