# oneko
# Autogenerated from man page /usr/share/man/man6/oneko.6.gz
# using Deroffing man parser
complete -c oneko -o help --description 'Prints help message on usage.'
complete -c oneko -o tora --description 'Make cat into "tora-neko", a cat wite tiger-like stripe.'
complete -c oneko -o dog --description 'Runs a dog instead of a cat.'
complete -c oneko -o sakura --description 'Runs Sakura Kinomoto instead of a cat.'
complete -c oneko -o tomoyo --description 'Runs Tomoyo Daidouji instead of a cat.'
complete -c oneko -o time --description 'Sets interval timer which determine intervals f… [See Man Page]'
complete -c oneko -o speed --description 'Specify the distance where cat jumps at one mov… [See Man Page]'
complete -c oneko -o idle --description 'Specify the threshold of the speed which ``mous… [See Man Page]'
complete -c oneko -o name --description 'Specify the window name of cat.'
complete -c oneko -o towindow --description 'When  oneko starts with this option, you must s… [See Man Page]'
complete -c oneko -o toname --description 'Specify the window name of target to make cat c… [See Man Page]'
complete -c oneko -o tofocus --description 'Makes cat run to and on top of focus window.'
complete -c oneko -o position --description 'Specify X and Y offsets in pixels to adjust pos… [See Man Page]'
complete -c oneko -o rv --description 'Reverse background color and foreground color.'
complete -c oneko -o noshape --description 'Don\'t use SHAPE extension.'
complete -c oneko -o fg --description 'Foreground color.'
complete -c oneko -o bg --description 'Background color.'
complete -c oneko -o cursor --description 'Specify a cursos number to set when quitting.'

