# openbox
# Autogenerated from man page /usr/share/man/man1/openbox.1.gz
# using Type1
complete -c openbox -l sm-disable --description 'Disable connection to session manager.'
complete -c openbox -l sm-client-id --description 'Specify session management \\s-1ID. \\s0.'
complete -c openbox -l sm-save-file --description 'Specify file to load a saved session from.'
complete -c openbox -l replace --description 'Replace the currently running window manager.'
complete -c openbox -l help --description 'Display some help and exit.'
complete -c openbox -l version --description 'Display the version and exit.'
complete -c openbox -l sync --description 'Run in synchronous mode (this is slow and meant… [See Man Page]'

