# origtargz
# Autogenerated from man page /usr/share/man/man1/origtargz.1.gz
# using Type1
complete -c origtargz -s p -l path --description 'Add directory to the list of locations to searc… [See Man Page]'
complete -c origtargz -s u -l 'unpack[' --description 'Unpack the downloaded orig tarball to the curre… [See Man Page]'
complete -c origtargz -l unpack --description 'If the current directory contains only a debian… [See Man Page]'
complete -c origtargz -s d -l download-only --description 'Alias for --unpack=no.'
complete -c origtargz -s t -l tar-only --description 'When using apt-get source, pass --tar-only to it.'

