# p11-kit
# Autogenerated from man page /usr/share/man/man1/p11-kit.1.gz
# using Deroffing man parser
complete -c p11-kit -s l --description 'Lists all of the PKCS#11 modules provided.'
complete -c p11-kit -s v --description 'Turn on verbose mode.'
complete -c p11-kit -s h --description 'Print usage information.'

