# panel-test-applets
# Autogenerated from man page /usr/share/man/man1/panel-test-applets.1.gz
# using Deroffing man parser
complete -c panel-test-applets -l help --description 'Display help  SEE ALSO .'

