# parallel
# Autogenerated from man page /usr/share/man/man1/parallel.1.gz
# using Deroffing man parser
complete -c parallel -s j --description 'Use to limit the number of jobs that are run at the same time.'
complete -c parallel -s l --description 'Wait as needed to avoid starting new jobs when … [See Man Page]'
complete -c parallel -s i --description 'Normally the command is passed the argument at … [See Man Page]'
complete -c parallel -s n --description 'Number of arguments to pass to a command at a time.'

