# perror
# Autogenerated from man page /usr/share/man/man1/perror.1.gz
# using Deroffing man parser
complete -c perror -l ndb --description 'option: shell> perror --ndb errorcode The meani… [See Man Page]'
complete -c perror -l help --description '.'
complete -c perror -l info --description '.'
complete -c perror -s I --description '.'
complete -c perror -s '?' --description '.'
complete -c perror -l silent --description '.'
complete -c perror -s s --description '.'
complete -c perror -l verbose --description '.'
complete -c perror -s v --description '.'
complete -c perror -l version --description '.'
complete -c perror -s V --description '.'

