# poedit
# Autogenerated from man page /usr/share/man/man1/poedit.1.gz
# using Deroffing man parser
complete -c poedit -s h -l help --description 'Display usage information and exit.'
complete -c poedit -l verbose --description 'Print verbose logging information.'

