# poeditor
# Autogenerated from man page /usr/share/man/man1/poeditor.1.gz
# using Deroffing man parser
complete -c poeditor -s h -l help --description 'Display usage information and exit.'
complete -c poeditor -l verbose --description 'Print verbose logging information.'

