# policyeditor
# Autogenerated from man page /usr/share/man/man1/policyeditor.1.gz
# using Deroffing man parser
complete -c policyeditor -o help --description 'Prints a short help text and exits.'
complete -c policyeditor -o file --description 'Specifies a policy file path to open.'
complete -c policyeditor -o codebase --description 'Specifies an applet codebase URL.'

