# praliases
# Autogenerated from man page /usr/share/man/man8/praliases.8.gz
# using Deroffing man parser
complete -c praliases -s C --description 'Read the specified sendmail configuration file … [See Man Page]'
complete -c praliases -s f --description 'Read the specified file instead of the configur… [See Man Page]'

