# pysetup3
# Autogenerated from man page /usr/share/man/man1/pysetup3.4.1.gz
# using Deroffing man parser
complete -c pysetup3 -l verbose --description 'run verbosely (default).'
complete -c pysetup3 -l quiet --description 'run quietly (turns verbosity off).'
complete -c pysetup3 -l dry-run --description 'don\'t actually do anything.'
complete -c pysetup3 -l help --description 'show detailed help message.'
complete -c pysetup3 -l no-user-cfg --description 'ignore pydistutils. cfg in your home directory.'
complete -c pysetup3 -l version --description 'Display the version.'

