# python3m
# Autogenerated from man page /usr/share/man/man1/python3m.1.gz
# using Deroffing man parser
complete -c python3m -s B --description 'Don\'t write . py[co] files on import.'
complete -c python3m -s b --description 'Issue warnings about str(bytes_instance), str(b… [See Man Page]'
complete -c python3m -s c --description 'Specify the command to execute (see next section).'
complete -c python3m -s d --description 'Turn on parser debugging output (for wizards on… [See Man Page]'
complete -c python3m -s E --description 'Ignore environment variables like PYTHONPATH an… [See Man Page]'
complete -c python3m -s h -s '?' -l help --description 'Prints the usage for the interpreter executable and exits.'
complete -c python3m -s i --description 'When a script is passed as first argument or th… [See Man Page]'
complete -c python3m -s I --description 'Run Python in isolated mode.  This also implies -E and -S.'
complete -c python3m -s m --description 'Searches  sys.'
complete -c python3m -s O --description 'Turn on basic optimizations.'
complete -c python3m -o OO --description 'Discard docstrings in addition to the -O optimizations.'
complete -c python3m -s q --description 'Do not print the version and copyright messages.'
complete -c python3m -s s --description 'Don\'t add user site directory to sys. path.'
complete -c python3m -s S --description 'Disable the import of the module site and the s… [See Man Page]'
complete -c python3m -s u --description 'Force the binary I/O layers of stdout and stder… [See Man Page]'
complete -c python3m -s v --description 'Print a message each time a module is initializ… [See Man Page]'
complete -c python3m -s V -l version --description 'Prints the Python version number of the executable and exits.'
complete -c python3m -s W --description 'Warning control.'
complete -c python3m -s X --description 'Set implementation specific option.'
complete -c python3m -s x --description 'Skip the first line of the source.'

