# python2-config
# Autogenerated from man page /usr/share/man/man1/python2-config.1.gz
# using Deroffing man parser
complete -c python2-config -l cflags --description 'print the C compiler flags.'
complete -c python2-config -l ldflags --description 'print the flags that should be passed to the linker.'
complete -c python2-config -l includes --description 'similar to --cflags but only with -I options (p… [See Man Page]'
complete -c python2-config -l libs --description 'similar to --ldflags but only with -l options (used libraries).'
complete -c python2-config -l prefix --description 'prints the prefix (base directory) under which … [See Man Page]'
complete -c python2-config -l exec-prefix --description 'print the prefix used for executable program di… [See Man Page]'
complete -c python2-config -l extension-suffix --description 'print suffix used for extension modules (includ… [See Man Page]'
complete -c python2-config -l configdir --description 'prints the path to the configuration directory … [See Man Page]'
complete -c python2-config -l help --description 'print the usage message.'

