# qemu-m68k
# Autogenerated from man page /usr/share/man/man1/qemu-m68k.1.gz
# using Deroffing man parser
complete -c qemu-m68k -s h --description 'Print this help.'
complete -c qemu-m68k -s g --description 'Wait gdb connection to port 1234.'
complete -c qemu-m68k -s L --description 'Set the elf interpreter prefix (default=/etc/qemu-binfmt/%M).'
complete -c qemu-m68k -s s --description 'Set the stack size in bytes (default=524288).'
complete -c qemu-m68k -s d --description 'Activate log (logfile=/tmp/qemu. log).'
complete -c qemu-m68k -s p --description 'Set the host page size to \'pagesize\'.'

