# qemu-microblazeel
# Autogenerated from man page /usr/share/man/man1/qemu-microblazeel.1.gz
# using Deroffing man parser
complete -c qemu-microblazeel -s h --description 'Print this help.'
complete -c qemu-microblazeel -s g --description 'Wait gdb connection to port 1234.'
complete -c qemu-microblazeel -s L --description 'Set the elf interpreter prefix (default=/etc/qemu-binfmt/%M).'
complete -c qemu-microblazeel -s s --description 'Set the stack size in bytes (default=524288).'
complete -c qemu-microblazeel -s d --description 'Activate log (logfile=/tmp/qemu. log).'
complete -c qemu-microblazeel -s p --description 'Set the host page size to \'pagesize\'.'

