# qemu-make-debian-root
# Autogenerated from man page /usr/share/man/man8/qemu-make-debian-root.8.gz
# using Deroffing man parser
complete -c qemu-make-debian-root -s k --description 'Keep file system.'
complete -c qemu-make-debian-root -s s --description 'Create a sparse image.  SEE ALSO qemu (1), qemu-img (1).'

