# qemu-i386
# Autogenerated from man page /usr/share/man/man1/qemu-i386.1.gz
# using Deroffing man parser
complete -c qemu-i386 -s h --description 'Print this help.'
complete -c qemu-i386 -s g --description 'Wait gdb connection to port 1234.'
complete -c qemu-i386 -s L --description 'Set the elf interpreter prefix (default=/etc/qemu-binfmt/%M).'
complete -c qemu-i386 -s s --description 'Set the stack size in bytes (default=524288).'
complete -c qemu-i386 -s d --description 'Activate log (logfile=/tmp/qemu. log).'
complete -c qemu-i386 -s p --description 'Set the host page size to \'pagesize\'.'

