# qemu-sparc32plus
# Autogenerated from man page /usr/share/man/man1/qemu-sparc32plus.1.gz
# using Deroffing man parser
complete -c qemu-sparc32plus -s h --description 'Print this help.'
complete -c qemu-sparc32plus -s g --description 'Wait gdb connection to port 1234.'
complete -c qemu-sparc32plus -s L --description 'Set the elf interpreter prefix (default=/etc/qemu-binfmt/%M).'
complete -c qemu-sparc32plus -s s --description 'Set the stack size in bytes (default=524288).'
complete -c qemu-sparc32plus -s d --description 'Activate log (logfile=/tmp/qemu. log).'
complete -c qemu-sparc32plus -s p --description 'Set the host page size to \'pagesize\'.'

