# qemu-io
# Autogenerated from man page /usr/share/man/man1/qemu-io.1.gz
# using Deroffing man parser
complete -c qemu-io -s c -l 'cmd<cmd>' --description 'Command to execute.'
complete -c qemu-io -s r -l read-only --description 'Export read-only.'
complete -c qemu-io -s s -l snapshot --description 'Use snapshot file.'
complete -c qemu-io -s n -l nocache --description 'Disable host cache.'
complete -c qemu-io -s g -l growable --description 'Allow file to grow (only applies to protocols).'
complete -c qemu-io -s m -l misalign --description 'Misalign allocations for O_DIRECT.'
complete -c qemu-io -s k -l native-aio --description 'Use kernel AIO implementation (on Linux only).'
complete -c qemu-io -s h -l help --description 'Display help and exit.'
complete -c qemu-io -l cmd --description 'Command to execute.'
complete -c qemu-io -s V -l version --description 'Output version information and exit SEE ALSO qe… [See Man Page]'

