# qemu-s390x
# Autogenerated from man page /usr/share/man/man1/qemu-s390x.1.gz
# using Deroffing man parser
complete -c qemu-s390x -s h --description 'Print this help.'
complete -c qemu-s390x -s g --description 'Wait gdb connection to port 1234.'
complete -c qemu-s390x -s L --description 'Set the elf interpreter prefix (default=/etc/qemu-binfmt/%M).'
complete -c qemu-s390x -s s --description 'Set the stack size in bytes (default=524288).'
complete -c qemu-s390x -s d --description 'Activate log (logfile=/tmp/qemu. log).'
complete -c qemu-s390x -s p --description 'Set the host page size to \'pagesize\'.'

