# qemu-mipsn32el
# Autogenerated from man page /usr/share/man/man1/qemu-mipsn32el.1.gz
# using Deroffing man parser
complete -c qemu-mipsn32el -s h --description 'Print this help.'
complete -c qemu-mipsn32el -s g --description 'Wait gdb connection to port 1234.'
complete -c qemu-mipsn32el -s L --description 'Set the elf interpreter prefix (default=/etc/qemu-binfmt/%M).'
complete -c qemu-mipsn32el -s s --description 'Set the stack size in bytes (default=524288).'
complete -c qemu-mipsn32el -s d --description 'Activate log (logfile=/tmp/qemu. log).'
complete -c qemu-mipsn32el -s p --description 'Set the host page size to \'pagesize\'.'

