# qemu-ppc64abi32
# Autogenerated from man page /usr/share/man/man1/qemu-ppc64abi32.1.gz
# using Deroffing man parser
complete -c qemu-ppc64abi32 -s h --description 'Print this help.'
complete -c qemu-ppc64abi32 -s g --description 'Wait gdb connection to port 1234.'
complete -c qemu-ppc64abi32 -s L --description 'Set the elf interpreter prefix (default=/etc/qemu-binfmt/%M).'
complete -c qemu-ppc64abi32 -s s --description 'Set the stack size in bytes (default=524288).'
complete -c qemu-ppc64abi32 -s d --description 'Activate log (logfile=/tmp/qemu. log).'
complete -c qemu-ppc64abi32 -s p --description 'Set the host page size to \'pagesize\'.'

