# rdmsr
# Autogenerated from man page /usr/share/man/man1/rdmsr.1.gz
# using Deroffing man parser
complete -c rdmsr -l help -s h --description 'Print a list of available options.'
complete -c rdmsr -l version -s V --description 'Print current version.'
complete -c rdmsr -l hexadecimal -s x --description 'Display output in hexadecimal (lower case).'
complete -c rdmsr -l capital-hex -s X --description 'Display output in hexadecimal (upper case).'
complete -c rdmsr -l decimal -s d --description 'Display output in signed decimal.'
complete -c rdmsr -l unsigned -s u --description 'Display output in unsigned decimal.'
complete -c rdmsr -l octal -s o --description 'Display output in octal.'
complete -c rdmsr -l c-language -s c --description 'Format output as a C language constant.'
complete -c rdmsr -l zero-pad -s 0 --description 'Output leading zeroes.'
complete -c rdmsr -l raw -s r --description 'Output raw binary.'
complete -c rdmsr -l all -s a --description 'All processors.'
complete -c rdmsr -l processor -s p --description 'Select processor number (default: 0).'
complete -c rdmsr -l bitfield -s f --description 'Output bits [h:l] only.'

