# reload
# Autogenerated from man page /usr/share/man/man8/reload.8.gz
# using Deroffing man parser
complete -c reload -l user --description 'User mode.'
complete -c reload -l session --description 'Connect to  init (8) daemon using the existing … [See Man Page]'
complete -c reload -l system --description 'Communication with the  init (8) daemon is norm… [See Man Page]'
complete -c reload -l dest --description 'Specifies the well-known name of the  init (8) … [See Man Page]'
complete -c reload -l no-wait --description 'Applies to the  start ", " stop ", " restart " … [See Man Page]'
complete -c reload -l quiet --description 'Reduces output of all commands to errors only.'
complete -c reload -s e -l enumerate --description '.'
complete -c reload -s i -l ignore-events --description '.'
complete -c reload -s w -l warn --description 'If specified, treat any unknown jobs and events as errors.'
complete -c reload -s g -l global --description 'Operate on the global job environment table.'
complete -c reload -s r -l retain --description 'If any of the specified variables are already s… [See Man Page]'
complete -c reload -l verbose --description 'the full path of the stale session file is displayed).'

