# remote-viewer
# Autogenerated from man page /usr/share/man/man1/remote-viewer.1.gz
# using Type1
complete -c remote-viewer -s h -l help --description 'Display command line help summary.'
complete -c remote-viewer -s V -l version --description 'Display program version number.'
complete -c remote-viewer -s v -l verbose --description 'Display information about the connection.'
complete -c remote-viewer -s z -l zoom --description 'Zoom level of the display window in percentage.  Range 10-400.'
complete -c remote-viewer -s f -l full-screen --description 'Start with the windows maximized to fullscreen.'
complete -c remote-viewer -s t -l title --description 'Set the window title to \\s-1TITLE\\s0.'
complete -c remote-viewer -l spice-controller --description 'Use the \\s-1SPICE\\s0 controller to initialize t… [See Man Page]'
complete -c remote-viewer -l debug --description 'Print debugging information.'
complete -c remote-viewer -s H -l hotkeys --description 'Set global hotkey bindings.'
complete -c remote-viewer -s k -l kiosk --description 'Start in kiosk mode.'

