# rename
# Autogenerated from man page /usr/share/man/man1/rename.ul.1.gz
# using Deroffing man parser
complete -c rename -l verbose --description 'Give visual feedback which files where renamed, if any.'
complete -c rename -l version --description 'Display version information and exit.'
complete -c rename -s s -l symlink --description 'Peform rename on symlink target.'
complete -c rename -l help --description 'Display help text and exit.  EXAMPLES Given the files foo1 , .'

