# restart
# Autogenerated from man page /usr/share/man/man8/restart.8.gz
# using Deroffing man parser
complete -c restart -l user --description 'User mode.'
complete -c restart -l session --description 'Connect to  init (8) daemon using the existing … [See Man Page]'
complete -c restart -l system --description 'Communication with the  init (8) daemon is norm… [See Man Page]'
complete -c restart -l dest --description 'Specifies the well-known name of the  init (8) … [See Man Page]'
complete -c restart -l no-wait --description 'Applies to the  start ", " stop ", " restart " … [See Man Page]'
complete -c restart -l quiet --description 'Reduces output of all commands to errors only.'
complete -c restart -s e -l enumerate --description '.'
complete -c restart -s i -l ignore-events --description '.'
complete -c restart -s w -l warn --description 'If specified, treat any unknown jobs and events as errors.'
complete -c restart -s g -l global --description 'Operate on the global job environment table.'
complete -c restart -s r -l retain --description 'If any of the specified variables are already s… [See Man Page]'
complete -c restart -l verbose --description 'the full path of the stale session file is displayed).'

