# ri2
# Autogenerated from man page /usr/share/man/man1/ri2.1.1.gz
# using Darwin man parser
complete -c ri2 -l version --description 'Prints the version of ri2.  Pp.'
complete -c ri2 -s T --description '.'
complete -c ri2 -l no-pager --description 'Send output directly to stdout, rather than to a pager.  Pp.'
complete -c ri2 -s d --description '.'
complete -c ri2 -l doc-dir --description 'List of directories from which to source docume… [See Man Page]'
complete -c ri2 -s f --description '.'
complete -c ri2 -l fmt --description '.'
complete -c ri2 -l format --description 'Format to use when displaying output: Pp ansi, … [See Man Page]'
complete -c ri2 -s i --description '.'
complete -c ri2 -l interactive --description 'This makes ri2 go into interactive mode.'
complete -c ri2 -l list-doc-dirs --description 'List the directories from which ri will source … [See Man Page]'
complete -c ri2 -l no-standard-docs --description 'Do not include documentation from the Ruby stan… [See Man Page]'
complete -c ri2 -s w --description '.'
complete -c ri2 -l width --description 'Set the width of the output.'

