# rmsgcat
# Autogenerated from man page /usr/share/man/man1/rmsgcat.1.gz
# using Deroffing man parser
complete -c rmsgcat -s o -l output --description 'Write output to specified file (default: the standard output).'
complete -c rmsgcat -l sort-by-msgid --description 'Sort output by msgid.'
complete -c rmsgcat -l sort-by-location --description 'Sort output by location.'
complete -c rmsgcat -l sort-by-file --description 'Sort output by location It is same as --sort-by… [See Man Page]'
complete -c rmsgcat -l '[no-]sort-output' --description 'Sort output by msgid It is same as --sort-by-ms… [See Man Page]'
complete -c rmsgcat -l no-location --description 'Remove location information.'
complete -c rmsgcat -l no-all-comments --description 'Remove all comments.'
complete -c rmsgcat -l width --description 'Set output page width (78).'
complete -c rmsgcat -l '[no-]wrap' --description 'Break long message lines, longer than the outpu… [See Man Page]'
complete -c rmsgcat -l no-fuzzy --description 'Ignore fuzzy entries.'
complete -c rmsgcat -l no-report-warning --description 'Don\'t report warning messages.'
complete -c rmsgcat -l no-obsolete-entries --description 'Don\'t output obsolete entries.'
complete -c rmsgcat -l remove-header-field --description 'Remove FIELD from header Specify this option mu… [See Man Page]'

