# sa-check_spamd
# Autogenerated from man page /usr/share/man/man1/sa-check_spamd.1.gz
# using Type1
complete -c sa-check_spamd -s c -l critical --description 'Critical ping response threshold in seconds.'
complete -c sa-check_spamd -s h -s '?' -l help --description 'Prints this usage message and exits.'
complete -c sa-check_spamd -s H -l hostname --description 'The hostname, or \\s-1IP\\s0 address, of the spam… [See Man Page]'
complete -c sa-check_spamd -s p -l port --description 'The port of the spamd service to ping.'
complete -c sa-check_spamd -l socketpath --description 'Connect to given \\s-1UNIX\\s0 domain socket.'
complete -c sa-check_spamd -s t -l timeout --description 'The maximum time to wait for a ping response.'
complete -c sa-check_spamd -s v -l verbose --description 'Display verbose debug output on \\s-1STDOUT. \\s0.'
complete -c sa-check_spamd -s V -l version --description 'Display version info on \\s-1STDOUT. \\s0.'

