# sa-compile
# Autogenerated from man page /usr/share/man/man1/sa-compile.1p.gz
# using Type1
complete -c sa-compile -l list --description 'Output the extracted base strings to \\s-1STDOUT… [See Man Page]'
complete -c sa-compile -l sudo --description 'Use \\f(CWsudo(8) to run code as \'root\' when wri… [See Man Page]'
complete -c sa-compile -l quiet --description 'Produce less diagnostic output.'
complete -c sa-compile -l keep-tmps --description 'Keep temporary files after the script completes… [See Man Page]'
complete -c sa-compile -s C -l configpath -l config-file --description 'Use the specified path for locating the distrib… [See Man Page]'
complete -c sa-compile -l siteconfigpath --description 'Use the specified path for locating site-specif… [See Man Page]'
complete -c sa-compile -l updatedir --description 'By default, \\f(CW\\*(C`sa-compile\\*(C\' will use … [See Man Page]'
complete -c sa-compile -l cf --description 'Add additional lines of configuration directly … [See Man Page]'
complete -c sa-compile -s p -l prefspath -l prefs-file --description 'Read user score preferences from prefs (usually… [See Man Page]'
complete -c sa-compile -s D -l debug --description 'Produce debugging output.'
complete -c sa-compile -s h -l help --description 'Print help message and exit.'

