# sa-update
# Autogenerated from man page /usr/share/man/man1/sa-update.1p.gz
# using Type1
complete -c sa-update -l channel --description 'sa-update can update multiple channels at the same time.'
complete -c sa-update -l channelfile --description 'Similar to the --channel option, except specify… [See Man Page]'
complete -c sa-update -l checkonly --description 'Only check if an update is available, don\'t act… [See Man Page]'
complete -c sa-update -l install --description 'Install updates \\*(L"offline\\*(R", from the named tar.'
complete -c sa-update -l allowplugins --description 'Allow downloaded updates to activate plugins.'
complete -c sa-update -l gpg -l nogpg --description 'sa-update by default will verify update archive… [See Man Page]'
complete -c sa-update -l gpgkey --description 'sa-update has the concept of \\*(L"release trust… [See Man Page]'
complete -c sa-update -l gpgkeyfile --description 'Similar to the --gpgkey option, except specify … [See Man Page]'
complete -c sa-update -l gpghomedir --description 'Specify a directory path to use as a storage ar… [See Man Page]'
complete -c sa-update -l import --description 'Use to import \\s-1GPG\\s0 key(s) from a file int… [See Man Page]'
complete -c sa-update -l refreshmirrors --description 'Force the list of sa-update mirrors for each ch… [See Man Page]'
complete -c sa-update -l updatedir --description 'By default, \\f(CW\\*(C`sa-update\\*(C\' will use t… [See Man Page]'
complete -c sa-update -s D -l debug --description 'Produce debugging output.'
complete -c sa-update -s h -l help --description 'Print help message and exit.'

