# sadt
# Autogenerated from man page /usr/share/man/man1/sadt.1.gz
# using Type1
complete -c sadt -s v -l verbose --description 'Make the output more verbose.'
complete -c sadt -s b -l built-source-tree --description 'Assume that the source tree is already built.'
complete -c sadt -l ignore-restriction --description 'Don\'t skip tests that declare the restriction.'

