# scan-build-3
# Autogenerated from man page /usr/share/man/man1/scan-build-3.6.1.gz
# using Darwin man parser
complete -c scan-build-3 -o analyze-headers --description 'Also analyze functions in #included files.'
complete -c scan-build-3 -o enable-checker --description 'Enable/disable checker_name.  See CHECKERS.'
complete -c scan-build-3 -s h --description 'Display this message.'
complete -c scan-build-3 -l help-checkers --description 'List default checkers, see CHECKERS.'
complete -c scan-build-3 -l html-title --description 'Specify the title used on generated HTML pages.'
complete -c scan-build-3 -s k --description 'Add a keep on going option to build_command.'
complete -c scan-build-3 -s o --description 'Target directory for HTML report files.'
complete -c scan-build-3 -o plist --description 'Output the results as a set of . plist files.'
complete -c scan-build-3 -o plist-html --description 'Output the results as a set of HTML and . plist files.'
complete -c scan-build-3 -l status-bugs --description 'Set exit status to 1 if it found potential bugs… [See Man Page]'
complete -c scan-build-3 -l use-c++ --description 'Guess the default compiler for your C++ and Objective-C++ code.'
complete -c scan-build-3 -l use-cc --description 'Guess the default compiler for your C and Objective-C code.'
complete -c scan-build-3 -s v --description 'Verbose output from scan-build-3 and the analyzer.'
complete -c scan-build-3 -s V --description 'View analysis results in a web browser when the… [See Man Page]'
complete -c scan-build-3 -o constraints --description 'Specify the contraint engine used by the analyzer.'
complete -c scan-build-3 -o maxloop --description 'Specifiy the number of times a block can be vis… [See Man Page]'
complete -c scan-build-3 -o no-failure-reports --description 'Do not create a failures subdirectory that incl… [See Man Page]'
complete -c scan-build-3 -o stats --description 'Generates visitation statistics for the project being analyzed.'
complete -c scan-build-3 -o store --description 'Specify the store model used by the analyzer.'

