# scan-view-3
# Autogenerated from man page /usr/share/man/man1/scan-view-3.6.1.gz
# using Deroffing man parser
complete -c scan-view-3 -s h -l help --description 'show this help message and exit.'
complete -c scan-view-3 -l host --description 'Host interface to listen on.  (default=127. 0. 0. 1).'
complete -c scan-view-3 -l port --description 'Port to listen on.  (default=8181).'
complete -c scan-view-3 -l debug --description 'Print additional debugging information.'
complete -c scan-view-3 -l auto-reload --description 'Automatically update module for each request.'
complete -c scan-view-3 -l no-browser --description 'Don\'t open a webbrowser on startup.'
complete -c scan-view-3 -l allow-all-hosts --description 'Allow connections from any host (access restricted to "127. 0.'

