# screenfetch
# Autogenerated from man page /usr/share/man/man1/screenfetch.1.gz
# using Deroffing man parser
complete -c screenfetch -s v --description 'Verbose output.'
complete -c screenfetch -s o --description 'Allows for setting script variables on the command line.'
complete -c screenfetch -s n --description 'Do not display ASCII distribution logo.'
complete -c screenfetch -s N --description 'Strip all color from output.'
complete -c screenfetch -s t --description 'Truncate output based on terminal width (Experimental!).'
complete -c screenfetch -s p --description 'Output in portrait mode, with logo above info.'
complete -c screenfetch -o 's(u)' --description 'Using this flag tells the script that you want … [See Man Page]'
complete -c screenfetch -s c --description 'You may change the outputted colors with -c.'
complete -c screenfetch -s S --description 'Here you can specify a custom screenshot comman… [See Man Page]'
complete -c screenfetch -s D --description 'Here you can specify your distribution for the script to use.'
complete -c screenfetch -s A --description 'Here you can specify the distribution art that … [See Man Page]'
complete -c screenfetch -s E --description 'Suppress output of errors.'
complete -c screenfetch -s V -l version --description 'Display current script version.'
complete -c screenfetch -s h -l help --description 'Display this help.'

