# sensors-detect
# Autogenerated from man page /usr/share/man/man8/sensors-detect.8.gz
# using Deroffing man parser
complete -c sensors-detect -l auto --description 'Run in automatic, non-interactive mode.'

