# sound-monitor_applet
# Autogenerated from man page /usr/share/man/man1/sound-monitor_applet.1.gz
# using Deroffing man parser
complete -c sound-monitor_applet -l activate-goad-server --description '(Internal use only) GOAD server ID to activate.'

