# speedometer
# Autogenerated from man page /usr/share/man/man1/speedometer.1.gz
# using Type1
complete -c speedometer -s b --description 'Use old blocky display instead of smoothed disp… [See Man Page]'
complete -c speedometer -s f --description 'Display download speed with progress bar.'
complete -c speedometer -s i --description 'Interval in seconds.  Examples: 5 or 0. 25".  Default is 1.'
complete -c speedometer -s p --description 'Use plain-text display (one tap only).'
complete -c speedometer -o rx --description 'Display bytes received on network interface.'
complete -c speedometer -o tx --description 'Display bytes transmitted on network interface.'

