# ssdiff
# Autogenerated from man page /usr/share/man/man1/ssdiff.1.gz
# using Deroffing man parser
complete -c ssdiff -s x -l xml --description 'Display differences in xml format  . SS "Help options".'
complete -c ssdiff -s V -l version --description 'Display ssdiff\'s version.'
complete -c ssdiff -s '?' -l help --description 'Display the supported options EXAMPLE To compar… [See Man Page]'

