# swapoff
# Autogenerated from man page /usr/share/man/man8/swapoff.8.gz
# using Deroffing man parser
complete -c swapoff -s a -l all --description 'All devices marked as ``swap\'\' in  /etc/fstab a… [See Man Page]'
complete -c swapoff -s d -l discard --description 'Enable swap discards, if the swap backing devic… [See Man Page]'
complete -c swapoff -s e -l ifexists --description 'Silently skip devices that do not exist.'
complete -c swapoff -s f -l fixpgsz --description 'Reinitialize (exec /sbin/mkswap) the swap space… [See Man Page]'
complete -c swapoff -s h -l help --description 'Display help text and exit.'
complete -c swapoff -s L --description 'Use the partition that has the specified R label .'
complete -c swapoff -s p -l priority --description 'Specify the priority of the swap device.'
complete -c swapoff -s s -l summary --description 'Display swap usage summary by device.'
complete -c swapoff -l show --description 'Display definable device table similar to  --summary output.'
complete -c swapoff -l noheadings --description 'Do not print headings when displaying  --show output.'
complete -c swapoff -l raw --description 'Display  --show output without aligning table columns.'
complete -c swapoff -l bytes --description 'Display swap size in bytes in  --show output in… [See Man Page]'
complete -c swapoff -s U --description 'Use the partition that has the specified R uuid .'
complete -c swapoff -s v -l verbose --description 'Be verbose.'
complete -c swapoff -s V -l version --description 'Display version information and exit.'

