# sylpheed
# Autogenerated from man page /usr/share/man/man1/sylpheed.1.gz
# using Type1
complete -c sylpheed -l compose --description 'Opens composition window, with some fields pres… [See Man Page]'
complete -c sylpheed -l attach --description 'Opens composition window with specified files attached.'
complete -c sylpheed -l receive --description 'Receives new messages.'
complete -c sylpheed -l receive-all --description 'Receives new messages for all accounts.'
complete -c sylpheed -l send --description 'Sends all queued messages.'
complete -c sylpheed -l status --description 'Shows the total number of messages.'
complete -c sylpheed -l status-full --description 'Shows the status of each given folder.'
complete -c sylpheed -l open --description 'Opens the existing message in a new window.'
complete -c sylpheed -l configdir --description 'Use given directory as configuration directory.'
complete -c sylpheed -l exit --description 'Makes a running Sylpheed to exit, then exits.'
complete -c sylpheed -l debug --description 'Enables debug mode.'
complete -c sylpheed -l safe-mode --description 'Enables safe mode.  Plugins won\'t be loaded in this mode.'
complete -c sylpheed -l help --description 'Displays a brief help screen and exits.'

