# sync-available
# Autogenerated from man page /usr/share/man/man8/sync-available.8.gz
# using Deroffing man parser
complete -c sync-available -l version --description 'Output the name and version of the program onto… [See Man Page]'
complete -c sync-available -l help --description 'Give a brief usage statement on the standard output stream.'

