# systemd-tmpfiles-setup
# Autogenerated from man page /usr/share/man/man8/systemd-tmpfiles-setup.service.8.gz
# using Deroffing man parser
complete -c systemd-tmpfiles-setup -l create --description 'If this option is passed, all files and directo… [See Man Page]'
complete -c systemd-tmpfiles-setup -l clean --description 'If this option is passed, all files and directo… [See Man Page]'
complete -c systemd-tmpfiles-setup -l remove --description 'If this option is passed, the contents of direc… [See Man Page]'
complete -c systemd-tmpfiles-setup -l boot --description 'Also execute lines with an exclamation mark.'
complete -c systemd-tmpfiles-setup -l prefix --description 'Only apply rules with paths that start with the… [See Man Page]'
complete -c systemd-tmpfiles-setup -l exclude-prefix --description 'Ignore rules with paths that start with the specified prefix.'
complete -c systemd-tmpfiles-setup -l root --description 'Takes a directory path as an argument.'
complete -c systemd-tmpfiles-setup -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-tmpfiles-setup -l version --description 'Print a short version string and exit.'

