# tracepath
# Autogenerated from man page /usr/share/man/man8/tracepath.8.gz
# using Type1
complete -c tracepath -s n --description 'Print primarily IP addresses numerically.'
complete -c tracepath -s b --description 'Print both of host names and IP addresses.'
complete -c tracepath -s l --description 'Sets the initial packet length to pktlen instea… [See Man Page]'
complete -c tracepath -o 'm/term>' --description 'Set maximum hops (or maximum TTLs) to max_hops instead of 30.'

