# tunelp
# Autogenerated from man page /usr/share/man/man8/tunelp.8.gz
# using Deroffing man parser
complete -c tunelp -s i -l irq --description 'specifies the IRQ to use for the parallel port in question.'
complete -c tunelp -s t -l time --description 'is the amount of time in jiffies that the drive… [See Man Page]'
complete -c tunelp -s c -l chars --description 'is the number of times to try to output a chara… [See Man Page]'
complete -c tunelp -s w -l wait --description 'is the number of usec we wait while playing wit… [See Man Page]'
complete -c tunelp -s a -l abort --description 'This is whether to abort on printer error - the… [See Man Page]'
complete -c tunelp -s o -l check-status --description 'This option is much like -a.'
complete -c tunelp -s C -l careful --description 'This option adds extra ("careful") error checking.'
complete -c tunelp -s s -l status --description 'This option returns the current printer status,… [See Man Page]'
complete -c tunelp -s T -l trust-irq --description 'This option is obsolete.  It was added in Linux 2. 1.'
complete -c tunelp -s r -l reset --description 'This option resets the port.'
complete -c tunelp -s q -l print-irq --description 'This option sets printing the display of the cu… [See Man Page]'

