# udevd
# Autogenerated from man page /usr/share/man/man8/udevd.8.gz
# using Deroffing man parser
complete -c udevd -l daemon --description 'Detach and run in the background.'
complete -c udevd -l debug --description 'Print debug messages to standard error.'
complete -c udevd -l children-max --description 'Limit the number of events executed in parallel.'
complete -c udevd -l exec-delay --description 'Delay the execution of RUN instructions by the … [See Man Page]'
complete -c udevd -l event-timeout --description 'Set the number of seconds to wait for events to finish.'
complete -c udevd -l resolve-names --description 'Specify when systemd-udevd should resolve names… [See Man Page]'
complete -c udevd -l help --description 'Print a short help text and exit.'
complete -c udevd -l version --description 'Print a short version string and exit.'

