# unity-control-center
# Autogenerated from man page /usr/share/man/man1/unity-control-center.1.gz
# using Deroffing man parser
complete -c unity-control-center -s '?' -l help --description 'Prints a short help text and exits.'
complete -c unity-control-center -l version --description 'Prints the program version and exits.'
complete -c unity-control-center -s v -l verbose --description 'Enables verbose mode.'
complete -c unity-control-center -s o -l overview --description 'Opens the overview.'

