# unshar
# Autogenerated from man page /usr/share/man/man1/unshar.1.gz
# using Type1
complete -c unshar -s d -l directory --description 'unpack into the directory dir.'
complete -c unshar -s c -l overwrite --description 'overwrite any pre-existing files.'
complete -c unshar -s f -l force --description 'This is an alias for the --overwrite option.'
complete -c unshar -s E -l split-at --description 'split input on split-mark lines.'
complete -c unshar -s e -l exit-0 --description 'split input on "exit 0" lines.'
complete -c unshar -s D -l debug --description 'debug the shell code.'
complete -c unshar -s h -l help --description 'Display usage information and exit.'
complete -c unshar -s '!' -l more-help --description 'Pass the extended usage information through a pager.'
complete -c unshar -s R -l save-opts --description 'Save the option state to cfgfile.'
complete -c unshar -s r -l load-opts -l no-load-opts --description 'Load options from cfgfile.'

