# upstart-dbus-bridge
# Autogenerated from man page /usr/share/man/man8/upstart-dbus-bridge.8.gz
# using Deroffing man parser
complete -c upstart-dbus-bridge -l always --description 'Always emit events on receipt of D-Bus signal r… [See Man Page]'
complete -c upstart-dbus-bridge -l daemon --description 'Detach and run in the background. \\".'
complete -c upstart-dbus-bridge -l debug --description 'Enable debugging output. \\".'
complete -c upstart-dbus-bridge -l help --description 'Show brief usage summary. \\".'
complete -c upstart-dbus-bridge -l session --description 'Monitor signals on the D-Bus session bus. \\".'
complete -c upstart-dbus-bridge -l system --description 'Monitor signals on the D-Bus system bus. \\".'
complete -c upstart-dbus-bridge -l user --description 'User-session mode: connect to Upstart via the u… [See Man Page]'
complete -c upstart-dbus-bridge -l bus-name --description 'Set a name for the bus to be passed as an addit… [See Man Page]'
complete -c upstart-dbus-bridge -l verbose --description 'Enable verbose output.'

