# urlgrabber
# Autogenerated from man page /usr/share/man/man1/urlgrabber.1.gz
# using Deroffing man parser
complete -c urlgrabber -l help -s h --description 'help page specifying available options to the binary program.'
complete -c urlgrabber -l copy-local --description 'ignored except for file:// urls, in which case … [See Man Page]'
complete -c urlgrabber -l throttle --description 'if it\'s an int, it\'s the bytes/second throttle limit.'
complete -c urlgrabber -l bandwidth --description 'the nominal max bandwidth in bytes/second.'
complete -c urlgrabber -l range --description 'a tuple of the form first_byte,last_byte descri… [See Man Page]'
complete -c urlgrabber -l user-agent --description 'the user-agent string provide if the url is HTTP.'
complete -c urlgrabber -l retry --description 'the number of times to retry the grab before bailing.'
complete -c urlgrabber -l retrycodes --description 'a sequence of errorcodes (values of e.'

