# uudecode
# Autogenerated from man page /usr/share/man/man1/uudecode.1.gz
# using Type1
complete -c uudecode -s o -l output-file --description 'direct output to file.'
complete -c uudecode -s c -l ignore-chmod --description 'ignore fchmod(3P) errors.'
complete -c uudecode -s h -l help --description 'Display usage information and exit.'
complete -c uudecode -s '!' -l more-help --description 'Pass the extended usage information through a pager.'
complete -c uudecode -s R -l save-opts --description 'Save the option state to cfgfile.'
complete -c uudecode -s r -l load-opts -l no-load-opts --description 'Load options from cfgfile.'

