# uuencode
# Autogenerated from man page /usr/share/man/man1/uuencode.1.gz
# using Type1
complete -c uuencode -s m -l base64 --description 'convert using base64.'
complete -c uuencode -s e -l encode-file-name --description 'encode the output file name.'
complete -c uuencode -s h -l help --description 'Display usage information and exit.'
complete -c uuencode -s '!' -l more-help --description 'Pass the extended usage information through a pager.'
complete -c uuencode -s R -l save-opts --description 'Save the option state to cfgfile.'
complete -c uuencode -s r -l load-opts -l no-load-opts --description 'Load options from cfgfile.'

