# vacation
# Autogenerated from man page /usr/share/man/man1/vacation.sendmail.1.gz
# using Deroffing man parser
complete -c vacation -s a --description 'Handle messages for  alias in the same manner a… [See Man Page]'
complete -c vacation -s C --description 'Specify pathname of the sendmail configuration file.'
complete -c vacation -s d --description 'Send error/debug messages to stderr instead of syslog.'
complete -c vacation -s f --description 'Use  filename as name of the database instead of R ~/.'
complete -c vacation -s i --description 'Initialize the vacation database files.'
complete -c vacation -s I --description 'Same as  -i (for backwards compatibility).'
complete -c vacation -s j --description 'Respond to the message regardless of whether th… [See Man Page]'
complete -c vacation -s l --description 'List the content of the vacation database file … [See Man Page]'
complete -c vacation -s m --description 'Use  filename as name of the file containing th… [See Man Page]'
complete -c vacation -s R --description 'Set the reply envelope sender address.'
complete -c vacation -s r --description 'Set the reply interval to  interval days.'
complete -c vacation -s s --description 'Use  address instead of the incoming message se… [See Man Page]'
complete -c vacation -s t --description 'Ignored, available only for compatibility with … [See Man Page]'
complete -c vacation -s U --description 'Do not attempt to lookup   login in the password file.'
complete -c vacation -s x --description 'Reads an exclusion list from stdin (one address per line).'
complete -c vacation -s z --description 'Set the sender of the vacation message to ``<>\'… [See Man Page]'
complete -c vacation -l eric --description '.'

