# VBoxManage
# Autogenerated from man page /usr/share/man/man1/VBoxManage.1.gz
# using Deroffing man parser
complete -c VBoxManage -l 'version]' --description 'print version number and exit.'
complete -c VBoxManage -l 'nologo]' --description 'suppress the logo.'
complete -c VBoxManage -o 'l]' --description 'vms|runningvms|ostypes|hostdvds|hostfloppies| b… [See Man Page]'
complete -c VBoxManage -l name --description '[--groups <group>, .'
complete -c VBoxManage -l passwordfile --description '<domain> [--allowlocallogon <yes|no>] | telepor… [See Man Page]'
complete -c VBoxManage -l password --description 'plugcpu <id> unplugcpu <id> cpuexecutioncap <1-100>.'
complete -c VBoxManage -l storagectl --description '[--port <number>] [--device <number>] [--type d… [See Man Page]'
complete -c VBoxManage -l limit --description 'set <name>.'
complete -c VBoxManage -l filename --description '[--size <megabytes>|--sizebyte <bytes>] [--diff… [See Man Page]'
complete -c VBoxManage -l target --description '.'
complete -c VBoxManage -l action --description '[--active yes|no] (yes) [--vendorid <XXXX>] (nu… [See Man Page]'
complete -c VBoxManage -l hostpath --description '[--transient] [--readonly] [--automount].'
complete -c VBoxManage -l image -l username --description '[--passwordfile <file> | --password <password>]… [See Man Page]'
complete -c VBoxManage -l 'cmd-set]' --description '<logdbg-settings|logrel-settings> [[opt] what .'
complete -c VBoxManage -l 'ip<ipv4>' --description '.'
complete -c VBoxManage -l 'ipv6<ipv6>' --description 'create | remove <name>.'
complete -c VBoxManage -l ifname --description '[--ip <ip_address>.'
complete -c VBoxManage -l netmask --description '.'
complete -c VBoxManage -l lowerip --description '.'
complete -c VBoxManage -l upperip --description '[--enable | --disable].'

