# vboxmanage
# Autogenerated from man page /usr/share/man/man1/vboxmanage.1.gz
# using Deroffing man parser
complete -c vboxmanage -l 'version]' --description 'print version number and exit.'
complete -c vboxmanage -l 'nologo]' --description 'suppress the logo.'
complete -c vboxmanage -o 'l]' --description 'vms|runningvms|ostypes|hostdvds|hostfloppies| b… [See Man Page]'
complete -c vboxmanage -l name --description '[--groups <group>, .'
complete -c vboxmanage -l passwordfile --description '<domain> [--allowlocallogon <yes|no>] | telepor… [See Man Page]'
complete -c vboxmanage -l password --description 'plugcpu <id> unplugcpu <id> cpuexecutioncap <1-100>.'
complete -c vboxmanage -l storagectl --description '[--port <number>] [--device <number>] [--type d… [See Man Page]'
complete -c vboxmanage -l limit --description 'set <name>.'
complete -c vboxmanage -l filename --description '[--size <megabytes>|--sizebyte <bytes>] [--diff… [See Man Page]'
complete -c vboxmanage -l target --description '.'
complete -c vboxmanage -l action --description '[--active yes|no] (yes) [--vendorid <XXXX>] (nu… [See Man Page]'
complete -c vboxmanage -l hostpath --description '[--transient] [--readonly] [--automount].'
complete -c vboxmanage -l image -l username --description '[--passwordfile <file> | --password <password>]… [See Man Page]'
complete -c vboxmanage -l 'cmd-set]' --description '<logdbg-settings|logrel-settings> [[opt] what .'
complete -c vboxmanage -l 'ip<ipv4>' --description '.'
complete -c vboxmanage -l 'ipv6<ipv6>' --description 'create | remove <name>.'
complete -c vboxmanage -l ifname --description '[--ip <ip_address>.'
complete -c vboxmanage -l netmask --description '.'
complete -c vboxmanage -l lowerip --description '.'
complete -c vboxmanage -l upperip --description '[--enable | --disable].'

