# virtfs-proxy-helper
# Autogenerated from man page /usr/share/man/man1/virtfs-proxy-helper.1.gz
# using Type1
complete -c virtfs-proxy-helper -s h --description 'Display help and exit.'
complete -c virtfs-proxy-helper -s p -l path --description 'Path to export for proxy filesystem driver.'
complete -c virtfs-proxy-helper -s f -l fd --description 'Use given file descriptor as socket descriptor … [See Man Page]'
complete -c virtfs-proxy-helper -s s -l socket --description 'Creates named socket file for communicating wit… [See Man Page]'
complete -c virtfs-proxy-helper -s u -l uid -s g -l gid --description 'uid:gid combination to give access to named socket file.'

