# virt-viewer
# Autogenerated from man page /usr/share/man/man1/virt-viewer.1.gz
# using Type1
complete -c virt-viewer -s h -l help --description 'Display command line help summary.'
complete -c virt-viewer -s V -l version --description 'Display program version number.'
complete -c virt-viewer -s v -l verbose --description 'Display information about the connection.'
complete -c virt-viewer -s c -l connect --description 'Specify the hypervisor connection \\s-1URI\\s0.'
complete -c virt-viewer -s w -l wait --description 'Wait for the domain to start up before attempti… [See Man Page]'
complete -c virt-viewer -s r -l reconnect --description 'Automatically reconnect to the domain if it shu… [See Man Page]'
complete -c virt-viewer -s z -l zoom --description 'Zoom level of the display window in percentage.  Range 10-400.'
complete -c virt-viewer -s d -l direct --description 'Do not attempt to tunnel the console over \\s-1S… [See Man Page]'
complete -c virt-viewer -s a -l attach --description 'Instead of making a direct \\s-1TCP/UNIX\\s0 sock… [See Man Page]'
complete -c virt-viewer -s f -l full-screen --description 'Start with the window maximised to fullscreen.'
complete -c virt-viewer -l debug --description 'Print debugging information.'
complete -c virt-viewer -s H -l hotkeys --description 'Set global hotkey bindings.'
complete -c virt-viewer -s k -l kiosk --description 'Start in kiosk mode.'

