# virt-convert
# Autogenerated from man page /usr/share/man/man1/virt-convert.1.gz
# using Type1
complete -c virt-convert -s h -l help --description 'Show the help message and exit.'
complete -c virt-convert -l version --description 'Show program\'s version number and exit.'
complete -c virt-convert -l connect --description 'Connect to a non-default hypervisor.'
complete -c virt-convert -o i/--input-format --description 'Input format.'
complete -c virt-convert -o D/--disk-format --description 'Output disk format.'
complete -c virt-convert -l destination --description 'The directory to send converted/copied disk images.'
complete -c virt-convert -l noautoconsole --description 'Don\'t automatically try to connect to the guest console.'
complete -c virt-convert -l print-xml --description 'Print the generated libvirt \\s-1XML,\\s0 but do … [See Man Page]'
complete -c virt-convert -l dry-run --description 'Proceed through the conversion process, but don… [See Man Page]'
complete -c virt-convert -s q -l quiet --description 'Avoid verbose output.'

