# virt-clone
# Autogenerated from man page /usr/share/man/man1/virt-clone.1.gz
# using Type1
complete -c virt-clone -s h -l help --description 'Show the help message and exit.'
complete -c virt-clone -l version --description 'Show program\'s version number and exit.'
complete -c virt-clone -l connect --description 'Connect to a non-default hypervisor.'
complete -c virt-clone -s o -l original --description 'Name of the original guest to be cloned.'
complete -c virt-clone -l original-xml --description 'Libvirt guest xml file to use as the original guest.'
complete -c virt-clone -l auto-clone --description 'Generate a new guest name, and paths for new storage.'
complete -c virt-clone -s n -l name --description 'Name of the new guest virtual machine instance.'
complete -c virt-clone -s u -l uuid --description '\\s-1UUID\\s0 for the guest; if none is given a r… [See Man Page]'
complete -c virt-clone -s f -l file --description 'Path to the file, disk partition, or logical vo… [See Man Page]'
complete -c virt-clone -l force-copy --description 'Force cloning the passed disk target (\'hdc\', \'sda\', etc. ).'
complete -c virt-clone -l nonsparse --description 'Fully allocate the new storage if the path bein… [See Man Page]'
complete -c virt-clone -l preserve-data --description 'No storage is cloned: disk images specific by -… [See Man Page]'
complete -c virt-clone -s m -l mac --description 'Fixed \\s-1MAC\\s0 address for the guest; If this… [See Man Page]'
complete -c virt-clone -l print-xml --description 'Print the generated clone \\s-1XML\\s0 and exit without cloning.'
complete -c virt-clone -l replace --description 'Shutdown and remove any existing guest with the… [See Man Page]'

