# virt-manager
# Autogenerated from man page /usr/share/man/man1/virt-manager.1.gz
# using Type1
complete -c virt-manager -s h -l help --description 'Display command line help summary.'
complete -c virt-manager -l version --description 'Show virt-manager\'s version number and exit.'
complete -c virt-manager -s c -l connect --description 'Specify the hypervisor connection \\f(CW\\*(C`URI\\*(C\'.'
complete -c virt-manager -l debug --description 'List debugging output to the console (normally … [See Man Page]'
complete -c virt-manager -l no-fork --description 'Don\'t fork \\f(CW\\*(C`virt-manager\\*(C\' off into… [See Man Page]'
complete -c virt-manager -l no-conn-autostart --description 'Don\'t autostart any libvirt connections when la… [See Man Page]'
complete -c virt-manager -l show-DIALOG-WINDOW --description 'Display the corresponding \\f(CW\\*(C`DIALOG-WIND… [See Man Page]'
complete -c virt-manager -l show-domain-creator --description 'Display the wizard for creating new virtual machines.'
complete -c virt-manager -l show-domain-editor --description 'Display the dialog for editing properties of th… [See Man Page]'
complete -c virt-manager -l show-domain-performance --description 'Display the dialog for monitoring performance o… [See Man Page]'
complete -c virt-manager -l show-domain-console --description 'Display the virtual console of the virtual mach… [See Man Page]'
complete -c virt-manager -l show-host-summary --description 'Display the main window summarizing performance… [See Man Page]'

