# virt-image
# Autogenerated from man page /usr/share/man/man1/virt-image.1.gz
# using Type1
complete -c virt-image -s h -l help --description 'Show the help message and exit.'
complete -c virt-image -l version --description 'Show program\'s version number and exit.'
complete -c virt-image -l connect --description 'Connect to a non-default hypervisor.'
complete -c virt-image -s n -l name --description 'Name of the guest instance.'
complete -c virt-image -l memory --description 'Memory to allocate for the guest, in megabytes.'
complete -c virt-image -l vcpus --description 'Number of vcpus to configure for your guest.'
complete -c virt-image -l cpu --description 'Configure the \\s-1CPU\\s0 and \\s-1CPU\\s0 feature… [See Man Page]'
complete -c virt-image -l os-variant --description 'Optimize the guest configuration for a specific… [See Man Page]'
complete -c virt-image -s w -l network --description 'Connect the guest to the host network.'
complete -c virt-image -l graphics --description 'Specifies the graphical display configuration.'
complete -c virt-image -l print-xml --description 'Print the libvirt \\s-1XML,\\s0 but do not start the guest.'
complete -c virt-image -l boot --description 'The zero-based index of the boot record to use.'
complete -c virt-image -l replace --description 'Shutdown and remove any existing guest with the… [See Man Page]'
complete -c virt-image -l noreboot --description 'Prevent the domain automatically booting after … [See Man Page]'
complete -c virt-image -l skip-checksum --description 'Do not check disk images against checksums (if … [See Man Page]'

