# who-permits-upload
# Autogenerated from man page /usr/share/man/man1/who-permits-upload.1.gz
# using Type1
complete -c who-permits-upload -l dmfile -s d --description 'Retrieve the \\s-1DM\\s0 permission file from the… [See Man Page]'
complete -c who-permits-upload -l help -s h --description 'Display an usage summary and exit.'
complete -c who-permits-upload -l keyring -s s --description 'Use the supplied GnuPG keyrings to look-up \\s-1… [See Man Page]'
complete -c who-permits-upload -l search --description 'Modify the look-up behavior.'

