# wrmsr
# Autogenerated from man page /usr/share/man/man1/wrmsr.1.gz
# using Deroffing man parser
complete -c wrmsr -l help -s h --description 'Print a list of available options.'
complete -c wrmsr -l version -s V --description 'Print current version.'
complete -c wrmsr -l all -s a --description 'All processors.'
complete -c wrmsr -l processor -s p --description 'Select processor number (default: 0).'

