# wvdial
# Autogenerated from man page /usr/share/man/man1/wvdial.1.gz
# using Deroffing man parser
complete -c wvdial -s c -l chat --description 'Run wvdial as a chat replacement from within pp… [See Man Page]'
complete -c wvdial -s C -l config --description 'Run wvdial with CONFIGFILE as the configuration… [See Man Page]'
complete -c wvdial -s n -l no-syslog --description 'Don\'t output debug information to the syslog da… [See Man Page]'

