# x-terminal-emulator
# Autogenerated from man page /usr/share/man/man1/x-terminal-emulator.1.gz
# using Type1
complete -c x-terminal-emulator -s s -l show-hide --description 'Toggle the visibility of guake.'
complete -c x-terminal-emulator -s p -l preferences --description 'Shows the preferences window of guake.'
complete -c x-terminal-emulator -s a -l about --description 'Shows the about window of guake.'

