# x-window-manager
# Autogenerated from man page /usr/share/man/man1/x-window-manager.1.gz
# using Type1
complete -c x-window-manager -l sm-disable --description 'Disable connection to session manager.'
complete -c x-window-manager -l sm-client-id --description 'Specify session management \\s-1ID. \\s0.'
complete -c x-window-manager -l sm-save-file --description 'Specify file to load a saved session from.'
complete -c x-window-manager -l replace --description 'Replace the currently running window manager.'
complete -c x-window-manager -l help --description 'Display some help and exit.'
complete -c x-window-manager -l version --description 'Display the version and exit.'
complete -c x-window-manager -l sync --description 'Run in synchronous mode (this is slow and meant… [See Man Page]'

