# x86_64-linux-gnu-python2
# Autogenerated from man page /usr/share/man/man1/x86_64-linux-gnu-python2.7-config.1.gz
# using Deroffing man parser
complete -c x86_64-linux-gnu-python2 -l cflags --description 'print the C compiler flags.'
complete -c x86_64-linux-gnu-python2 -l ldflags --description 'print the flags that should be passed to the linker.'
complete -c x86_64-linux-gnu-python2 -l includes --description 'similar to --cflags but only with -I options (p… [See Man Page]'
complete -c x86_64-linux-gnu-python2 -l libs --description 'similar to --ldflags but only with -l options (used libraries).'
complete -c x86_64-linux-gnu-python2 -l prefix --description 'prints the prefix (base directory) under which … [See Man Page]'
complete -c x86_64-linux-gnu-python2 -l exec-prefix --description 'print the prefix used for executable program di… [See Man Page]'
complete -c x86_64-linux-gnu-python2 -l extension-suffix --description 'print suffix used for extension modules (includ… [See Man Page]'
complete -c x86_64-linux-gnu-python2 -l configdir --description 'prints the path to the configuration directory … [See Man Page]'
complete -c x86_64-linux-gnu-python2 -l help --description 'print the usage message.'

