# xarchiver
# Autogenerated from man page /usr/share/man/man1/xarchiver.1.gz
# using Deroffing man parser
complete -c xarchiver -s h -l help --description 'Show help options.'
complete -c xarchiver -l help-all --description 'Show all help options.'
complete -c xarchiver -l help-gtk --description 'Show GTK+ Options . SS "Application Options:".'
complete -c xarchiver -s x -l extract-to --description 'Extract archive to the destination directory and quits.'
complete -c xarchiver -s e -l extract --description 'Extract archive by asking the extraction directory and quits.'
complete -c xarchiver -s m -l multi-extract --description 'Multi-extract archives.'
complete -c xarchiver -s d -l add-to --description 'Add the given files by asking the name of the a… [See Man Page]'
complete -c xarchiver -s a -l add --description 'Add files to archive by asking their filenames and quits.'
complete -c xarchiver -s V -l version --description 'Show version and exit.'
complete -c xarchiver -l display --description 'X display to use.'

