# xcam
# Autogenerated from man page /usr/share/man/man1/xcam.1.gz
# using Deroffing man parser
complete -c xcam -l Buffer --description 'option is given, xcam  will use a 1024 kByte in… [See Man Page]'
complete -c xcam -l version --description 'option is given,  xcam will output its version number.'
complete -c xcam -l help --description 'flag prints a short summary of options.'

