# xclip
# Autogenerated from man page /usr/share/man/man1/xclip.1.gz
# using Deroffing man parser
complete -c xclip -s i -o in --description 'read text into X selection from standard input … [See Man Page]'
complete -c xclip -s o -o out --description 'print the selection to standard out (generally … [See Man Page]'
complete -c xclip -s f -o filter --description 'when xclip is invoked in the in mode with outpu… [See Man Page]'
complete -c xclip -s l -o loops --description 'number of X selection requests (pastes into X a… [See Man Page]'
complete -c xclip -s t -o target --description 'specify a particular data format using the given target atom.'
complete -c xclip -s d -o display --description 'X display to use (e. g.'
complete -c xclip -s h -o help --description 'show quick summary of options.'
complete -c xclip -o selection --description 'specify which X selection to use, options are "… [See Man Page]'
complete -c xclip -o version --description 'show version information.'
complete -c xclip -o silent --description 'fork into the background to wait for requests, … [See Man Page]'
complete -c xclip -o quiet --description 'show informational messages on the terminal and… [See Man Page]'
complete -c xclip -o verbose --description 'provide a running commentary of what xclip is doing.'
complete -c xclip -o noutf8 --description 'operate in legacy (i. e.'

