# xcowsay
# Autogenerated from man page /usr/share/man/man6/xcowsay.6.gz
# using Deroffing man parser
complete -c xcowsay -s h -l help --description 'Display usage information.'
complete -c xcowsay -s t -l time --description 'Display the cow for  time seconds.'
complete -c xcowsay -s r -l reading-speed --description 'Number of milliseconds to display the cow for e… [See Man Page]'
complete -c xcowsay -s f -l font --description 'Font for the speech bubble text.  Accepts Pango font strings.'
complete -c xcowsay -s d -l dream --description 'Display an image instead of text in the cow\'s bubble.'
complete -c xcowsay -l think --description 'Display a thought bubble instead of a speech bubble.'
complete -c xcowsay -l daemon --description 'Run xcowsay in daemon mode if DBus support has been enabled.'
complete -c xcowsay -l cow-size --description 'Size of the cow image.'
complete -c xcowsay -l image --description 'Use a different image instead of the cow.'
complete -c xcowsay -l monitor --description 'Make the cow appear on monitor N.'
complete -c xcowsay -l at --description 'Force that cow to appear at screen location (X,Y).'
complete -c xcowsay -l bubble-at --description 'Change position of bubble relative to where it … [See Man Page]'
complete -c xcowsay -l no-wrap --description 'Disable word wrapping when the bubble is too wi… [See Man Page]'
complete -c xcowsay -s l -l left --description 'Make the bubble appear on the left hand side of the cow.'
complete -c xcowsay -l debug --description 'Print messages about what  xcowsay is doing.'
complete -c xcowsay -l config --description 'command line option is passed  FILE will be pro… [See Man Page]'
complete -c xcowsay -s v -l version --description 'Print version information.  AUTHOR Written by Nick Gasson.'

