# xfce4-power-manager
# Autogenerated from man page /usr/share/man/man1/xfce4-power-manager.1.gz
# using Deroffing man parser
complete -c xfce4-power-manager -l no-daemon --description 'Starts the power manager in non-daemon mode: us… [See Man Page]'
complete -c xfce4-power-manager -l debug --description 'Have the power manager print debug messages to … [See Man Page]'
complete -c xfce4-power-manager -l dump --description 'Have the power manager print the configuration … [See Man Page]'
complete -c xfce4-power-manager -l restart --description 'Causes the running power manager to restart.'
complete -c xfce4-power-manager -l customize --description 'Shows the configuration dialog.'
complete -c xfce4-power-manager -l quit --description 'Causes any running instance of xfce4-power-manager to exit.'
complete -c xfce4-power-manager -l version --description 'Show the version information.'

