# xfce4-power-information
# Autogenerated from man page /usr/share/man/man1/xfce4-power-information.1.gz
# using Deroffing man parser
complete -c xfce4-power-information -s h -l help --description 'Show help options.'
complete -c xfce4-power-information -l help-all --description 'Show all help options.'
complete -c xfce4-power-information -l help-gtk --description 'Show GTK+ Options . PP GTK+ Options.'
complete -c xfce4-power-information -l class --description 'Program class as used by the window manager.'
complete -c xfce4-power-information -l name --description 'Program name as used by the window manager.'
complete -c xfce4-power-information -l screen --description 'X screen to use.'
complete -c xfce4-power-information -l sync --description 'Make X calls synchronous.'
complete -c xfce4-power-information -l gtk-module --description 'Load additional GTK+ modules.'
complete -c xfce4-power-information -l g-fatal-warnings --description 'Make all warnings fatal . SS "Application Options:".'
complete -c xfce4-power-information -s V -l version --description 'Version information.'
complete -c xfce4-power-information -l display --description 'X display to use.'

