# xfce4-power-manager-settings
# Autogenerated from man page /usr/share/man/man1/xfce4-power-manager-settings.1.gz
# using Deroffing man parser
complete -c xfce4-power-manager-settings -l debug --description 'Have the power manager print debug messages to … [See Man Page]'
complete -c xfce4-power-manager-settings -l socket-id --description 'Settings manager socket, used when xfce4-power-… [See Man Page]'
complete -c xfce4-power-manager-settings -l device-id --description 'Display a specific device by a specific UPower … [See Man Page]'

