# xfpm-power-backlight-helper
# Autogenerated from man page /usr/share/man/man1/xfpm-power-backlight-helper.1.gz
# using Deroffing man parser
complete -c xfpm-power-backlight-helper -s h -l help --description 'Show help options . SS "Application Options:".'
complete -c xfpm-power-backlight-helper -l set-brightness --description 'Set the current brightness.'
complete -c xfpm-power-backlight-helper -l get-brightness --description 'Get the current brightness.'
complete -c xfpm-power-backlight-helper -l get-max-brightness --description 'Get the number of brightness levels supported SEE ALSO.'

