# xmms2d
# Autogenerated from man page /usr/share/man/man1/xmms2d.1.gz
# using Deroffing man parser
complete -c xmms2d -s v -l verbose --description 'Increase verbosity.'
complete -c xmms2d -s q -l quiet --description 'Decrease verbosity.'
complete -c xmms2d -s p -l plugindir --description 'Use plugin directory R dir .'
complete -c xmms2d -s o -l output --description 'Use output plugin R plugin .'
complete -c xmms2d -s i -l ipc-socket --description 'Listen to socket at R url .'
complete -c xmms2d -s c -l conf --description 'Use configuration file R file .'
complete -c xmms2d -s s -l status-fd --description 'Write to filedescriptor  fd when started.'
complete -c xmms2d -l yes-run-as-root --description 'Allow  xmms2d to be run as root. SS Getting help.'
complete -c xmms2d -s h -s '?' -l help --description 'Display basic help information and exit.'
complete -c xmms2d -s V -l version --description 'Display version information.'

