# xpad
# Autogenerated from man page /usr/share/man/man1/xpad.1.gz
# using Deroffing man parser
complete -c xpad -s v -l version --description 'Display version information.'
complete -c xpad -s '?' -l help --description 'Display usage information.'
complete -c xpad -s h -l hide --description 'Hides existing pads on startup.'
complete -c xpad -s s -l show --description 'Shows existing pads on startup.'
complete -c xpad -s t -l toggle --description 'Toggle between showing and hiding each of the e… [See Man Page]'
complete -c xpad -s n -l new --description 'Open a new pad.'
complete -c xpad -s N -l no-new --description 'Prevents xpad from making a new pad on startup.'
complete -c xpad -s f -l new-from-file --description 'Create a new pad with the contents of a file.'
complete -c xpad -s q -l quit --description 'Closes all open pads and terminates the xpad processes.'

