# xscanimage
# Autogenerated from man page /usr/share/man/man1/xscanimage.1.gz
# using Deroffing man parser
complete -c xscanimage -l version --description 'option is given,  xscanimage will output its version number.'
complete -c xscanimage -l help --description 'flag prints a short summary of options.'
complete -c xscanimage -l display --description 'flag selects the X11 display used to present th… [See Man Page]'
complete -c xscanimage -l no-xshm --description 'flag requests not to use shared memory images.'
complete -c xscanimage -l sync --description 'flag requests a synchronous connection with the X11 server.'

