# xssstate
# Autogenerated from man page /usr/share/man/man1/xssstate.1.gz
# using Deroffing man parser
complete -c xssstate -s i --description 'show the idle time of X11, in milliseconds.'
complete -c xssstate -s s --description 'show the current state of the X screensaver.'
complete -c xssstate -s t --description 'will show the time that needs to be waited unti… [See Man Page]'
complete -c xssstate -s v --description 'show version information AUTHORS See the LICENS… [See Man Page]'

